In [1]:
import sys
import os
from pathlib import Path
import pandas as pd
from pandas.api.types import CategoricalDtype
import numpy as np
ROOT = Path.cwd().parents[1]
sys.path.append(str(ROOT))

from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.covariance import LedoitWolf
from itertools import product


import config.settings as settings
import src.produccion_x_equipo as crea_produccion
import src.extract_files as extract
import src.filter as filtra
import src.fc_prophet as fcProphet
#import src.produccion_x_equipo as produccion_x_equipo
import importlib
importlib.reload(filtra)
importlib.reload(fcProphet)
#import src.notebooks.TestFunctions as testfunctions
%load_ext autoreload
%autoreload 2

x is: 1

/home/jorge/Projects/Radioterapia/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [2]:
input_path = settings.DATA_DIR / "processed" / "produccion_radioterapia.csv"

df = pd.read_csv(input_path)

In [3]:
print(df.head(5))
print(df.groupby("tipo_dia")["ds"].size())

           ds    equipo   y  capacidad tipo_dia  novedad
0  2022-05-03   HALCYON  59         70  laboral  ninguna
1  2022-05-03   SYNERGY  41         65  laboral  ninguna
2  2022-05-03  SYNERGY2  32         47  laboral  ninguna
3  2022-05-03  SYNERGY3  34         47  laboral  ninguna
4  2022-05-04   HALCYON  64         70  laboral  ninguna
tipo_dia
festivo           347
fin de semana    2670
laboral          6347
Name: ds, dtype: int64

In [4]:
dt = df.copy()
dt ["ds"] = pd.to_datetime(dt["ds"])
print(dt.head(5))
print(dt.groupby("tipo_dia")["ds"].size())

          ds    equipo   y  capacidad tipo_dia  novedad
0 2022-05-03   HALCYON  59         70  laboral  ninguna
1 2022-05-03   SYNERGY  41         65  laboral  ninguna
2 2022-05-03  SYNERGY2  32         47  laboral  ninguna
3 2022-05-03  SYNERGY3  34         47  laboral  ninguna
4 2022-05-04   HALCYON  64         70  laboral  ninguna
tipo_dia
festivo           347
fin de semana    2670
laboral          6347
Name: ds, dtype: int64

In [5]:
dt = pd.get_dummies(dt, columns = ["tipo_dia","novedad"])

In [6]:
dt.columns = (
    dt.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+","_",regex=True)
    .str.replace(r"tipo_dia_","",regex=True)
    .str.replace("novedad_","",regex=False)
)
print(dt)

             ds      equipo   y  capacidad  festivo  fin_de_semana  laboral  \
0    2022-05-03     HALCYON  59         70    False          False     True
1    2022-05-03     SYNERGY  41         65    False          False     True
2    2022-05-03    SYNERGY2  32         47    False          False     True
3    2022-05-03    SYNERGY3  34         47    False          False     True
4    2022-05-04     HALCYON  64         70    False          False     True
...         ...         ...  ..        ...      ...            ...      ...
9359 2026-04-30  EDGE2_6137   0          0     True          False    False
9360 2026-04-30     HALCYON   0          0     True          False    False
9361 2026-04-30    HALCYON3   0          0     True          False    False
9362 2026-04-30    HALCYON4   0          0     True          False    False
9363 2026-04-30    HALCYON5   0          0     True          False    False

      control_de_calidad  falla  mantenimiento  ninguna
0                  False  False          False     True
1                  False  False          False     True
2                  False  False          False     True
3                  False  False          False     True
4                  False  False          False     True
...                  ...    ...            ...      ...
9359               False  False          False     True
9360               False  False          False     True
9361               False  False          False     True
9362               False  False          False     True
9363               False  False          False     True

[9364 rows x 11 columns]

In [7]:
range_dates = pd.date_range(dt["ds"].min(), dt["ds"].max(), freq = "D")
equipos = sorted(dt["equipo"].unique())

complete_index = pd.MultiIndex.from_product(
    [range_dates, equipos],
    names = ["ds", "equipo"]
)

dt = (dt.set_index(["ds", "equipo"])
      .reindex(complete_index)
      .reset_index()
     )

In [8]:
print(dt.columns)
print(dt.head(5))

Index(['ds', 'equipo', 'y', 'capacidad', 'festivo', 'fin_de_semana', 'laboral',
       'control_de_calidad', 'falla', 'mantenimiento', 'ninguna'],
      dtype='object')
          ds      equipo     y  capacidad festivo fin_de_semana laboral  \
0 2022-05-03  EDGE1_6107   NaN        NaN     NaN           NaN     NaN
1 2022-05-03  EDGE2_6137   NaN        NaN     NaN           NaN     NaN
2 2022-05-03     HALCYON  59.0       70.0   False         False    True
3 2022-05-03    HALCYON3   NaN        NaN     NaN           NaN     NaN
4 2022-05-03    HALCYON4   NaN        NaN     NaN           NaN     NaN

  control_de_calidad  falla mantenimiento ninguna
0                NaN    NaN           NaN     NaN
1                NaN    NaN           NaN     NaN
2              False  False         False    True
3                NaN    NaN           NaN     NaN
4                NaN    NaN           NaN     NaN

In [9]:
dt = dt.drop(columns = ["laboral","ninguna"])
print(dt.head(5))

          ds      equipo     y  capacidad festivo fin_de_semana  \
0 2022-05-03  EDGE1_6107   NaN        NaN     NaN           NaN
1 2022-05-03  EDGE2_6137   NaN        NaN     NaN           NaN
2 2022-05-03     HALCYON  59.0       70.0   False         False
3 2022-05-03    HALCYON3   NaN        NaN     NaN           NaN
4 2022-05-03    HALCYON4   NaN        NaN     NaN           NaN

  control_de_calidad  falla mantenimiento
0                NaN    NaN           NaN
1                NaN    NaN           NaN
2              False  False         False
3                NaN    NaN           NaN
4                NaN    NaN           NaN

In [10]:
dt.groupby('equipo')['ds'].size()

equipo
EDGE1_6107    1459
EDGE2_6137    1459
HALCYON       1459
HALCYON3      1459
HALCYON4      1459
HALCYON5      1459
SYNERGY       1459
SYNERGY2      1459
SYNERGY3      1459
Name: ds, dtype: int64

In [11]:
dt["ds"] = pd.to_datetime(dt["ds"])
print(dt.columns)

Index(['ds', 'equipo', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

In [12]:
print(dt.head(5))

          ds      equipo     y  capacidad festivo fin_de_semana  \
0 2022-05-03  EDGE1_6107   NaN        NaN     NaN           NaN
1 2022-05-03  EDGE2_6137   NaN        NaN     NaN           NaN
2 2022-05-03     HALCYON  59.0       70.0   False         False
3 2022-05-03    HALCYON3   NaN        NaN     NaN           NaN
4 2022-05-03    HALCYON4   NaN        NaN     NaN           NaN

  control_de_calidad  falla mantenimiento
0                NaN    NaN           NaN
1                NaN    NaN           NaN
2              False  False         False
3                NaN    NaN           NaN
4                NaN    NaN           NaN

In [13]:
dt = dt.sort_values(["equipo", "ds"])
print(dt.head(5))

           ds      equipo   y  capacidad festivo fin_de_semana  \
0  2022-05-03  EDGE1_6107 NaN        NaN     NaN           NaN
9  2022-05-04  EDGE1_6107 NaN        NaN     NaN           NaN
18 2022-05-05  EDGE1_6107 NaN        NaN     NaN           NaN
27 2022-05-06  EDGE1_6107 NaN        NaN     NaN           NaN
36 2022-05-07  EDGE1_6107 NaN        NaN     NaN           NaN

   control_de_calidad falla mantenimiento
0                 NaN   NaN           NaN
9                 NaN   NaN           NaN
18                NaN   NaN           NaN
27                NaN   NaN           NaN
36                NaN   NaN           NaN

In [14]:
dt["capacidad"] = (
    dt.groupby("equipo")["capacidad"]
    .ffill()
    .bfill()
    .fillna(0)
    .astype(int)
)

dt["y"] = (
    dt.groupby("equipo")["y"]
    .ffill()
    .bfill()
    .fillna(0)
    .astype(int)
)

In [15]:
for col in ["festivo", "fin_de_semana", "control_de_calidad", "falla", "mantenimiento"]:
    if col in dt.columns:
        dt[col] = dt[col].astype("boolean").fillna(False).astype(bool)

In [16]:
print(dt.head(5))

           ds      equipo  y  capacidad  festivo  fin_de_semana  \
0  2022-05-03  EDGE1_6107  2         21    False          False
9  2022-05-04  EDGE1_6107  2         21    False          False
18 2022-05-05  EDGE1_6107  2         21    False          False
27 2022-05-06  EDGE1_6107  2         21    False          False
36 2022-05-07  EDGE1_6107  2         21    False          False

    control_de_calidad  falla  mantenimiento
0                False  False          False
9                False  False          False
18               False  False          False
27               False  False          False
36               False  False          False

In [17]:
dt.groupby('equipo')['ds'].size()

equipo
EDGE1_6107    1459
EDGE2_6137    1459
HALCYON       1459
HALCYON3      1459
HALCYON4      1459
HALCYON5      1459
SYNERGY       1459
SYNERGY2      1459
SYNERGY3      1459
Name: ds, dtype: int64

In [18]:


all_dates = pd.date_range(df["ds"].min(), df["ds"].max(), freq = "D")
equipos = sorted(df["equipo"].unique())

full_index = pd.MultiIndex.from_product(
    [all_dates, equipos],
    names = ["ds", "equipo"]
)

df = (df.set_index(["ds", "equipo"])
      .reindex(full_index)
      .reset_index()
     )

In [19]:
print(df.columns)

Index(['ds', 'equipo', 'y', 'capacidad', 'tipo_dia', 'novedad'], dtype='object')

In [20]:


all_dates = pd.date_range(df["ds"].min(), df["ds"].max(), freq = "D")
equipos = sorted(df["equipo"].unique())

full_index = pd.MultiIndex.from_product(
    [all_dates, equipos],
    names = ["ds", "equipo"]
)

df = (df.set_index(["ds", "equipo"])
      .reindex(full_index)
      .reset_index()
     )

In [21]:
df = df.sort_values(["equipo", "ds"])

In [22]:
print(df.head(4))

           ds      equipo   y  capacidad tipo_dia novedad
0  2022-05-03  EDGE1_6107 NaN        NaN      NaN     NaN
9  2022-05-04  EDGE1_6107 NaN        NaN      NaN     NaN
18 2022-05-05  EDGE1_6107 NaN        NaN      NaN     NaN
27 2022-05-06  EDGE1_6107 NaN        NaN      NaN     NaN

In [23]:
df["capacidad"] = (
    df.groupby("equipo")["capacidad"]
    .ffill()
    .bfill()
    .fillna(0)
    .astype(int)
)

df["y"] = (
    df.groupby("equipo")["y"]
    .ffill()
    .bfill()
    .fillna(0)
    .astype(int)
)

In [24]:
for col in ["novedad_Falla", "novedad_Mantenimiento", "novedad_ninguna"]:
    if col in df.columns:
        df[col] = df[col].astype("boolean").fillna(False).astype(bool)

In [25]:
df.groupby('equipo')['ds'].size()

equipo
EDGE1_6107    1459
EDGE2_6137    1459
HALCYON       1459
HALCYON3      1459
HALCYON4      1459
HALCYON5      1459
SYNERGY       1459
SYNERGY2      1459
SYNERGY3      1459
Name: ds, dtype: int64

In [26]:
db_train = pd.read_csv(settings.DATA_DIR / "processed"/ "demanda"/ "train" / "train_demand.csv")

print(db_train.head(3))

           ds      equipo   y  capacidad  festivo  fin_de_semana  \
0  2022-05-03  EDGE1_6107  59         70    False          False
1  2022-05-03  EDGE2_6137  59         70    False          False
2  2022-05-03     HALCYON  59         70    False          False

   control_de_calidad  falla  mantenimiento
0               False  False          False
1               False  False          False
2               False  False          False

In [27]:
db_val = pd.read_csv(settings.DATA_DIR / "processed" / "demanda" / "validation"/ "validation_demand.csv")

print(db_val.head(3))

           ds      equipo  y  capacidad  festivo  fin_de_semana  \
0  2026-01-01  EDGE1_6107  0          0     True          False
1  2026-01-01  EDGE2_6137  0          0     True          False
2  2026-01-01     HALCYON  0          0     True          False

   control_de_calidad  falla  mantenimiento
0               False  False          False
1               False  False          False
2               False  False          False

In [28]:
db_train_dates = pd.read_csv(settings.DATA_DIR / "processed"/ "demanda" / "train" / "train_dates.csv")
print(db_train_dates.head(5))

           ds
0  2022-05-03
1  2022-05-04
2  2022-05-05
3  2022-05-06
4  2022-05-07

In [29]:
db_val_dates = pd.read_csv(settings.DATA_DIR / "processed"/ "demanda" / "validation" / "val_dates.csv")
print(db_val_dates.head(5))

           ds
0  2026-01-01
1  2026-01-02
2  2026-01-03
3  2026-01-04
4  2026-01-05

In [30]:
#train_dates = db_train_dates["ds"].unique()
val_dates = db_val_dates["ds"].unique()
print(type(db_train_dates))
print(db_train_dates)

<class 'pandas.core.frame.DataFrame'>
              ds
0     2022-05-03
1     2022-05-04
2     2022-05-05
3     2022-05-06
4     2022-05-07
...          ...
1334  2025-12-27
1335  2025-12-28
1336  2025-12-29
1337  2025-12-30
1338  2025-12-31

[1339 rows x 1 columns]

In [31]:
db_full_train = pd.read_csv(settings.DATA_DIR / "processed" / "demanda"/ "produccion_radioterapia.csv")
print(db_full_train.shape)
print(db_full_train.columns)

(13131, 9)
Index(['ds', 'equipo', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

In [32]:
db_full_train.groupby('equipo')['ds'].size()

equipo
EDGE1_6107    1459
EDGE2_6137    1459
HALCYON       1459
HALCYON3      1459
HALCYON4      1459
HALCYON5      1459
SYNERGY       1459
SYNERGY2      1459
SYNERGY3      1459
Name: ds, dtype: int64

In [33]:
equipos = sorted(df['equipo'].unique())
print(equipos)

['EDGE1_6107', 'EDGE2_6137', 'HALCYON', 'HALCYON3', 'HALCYON4', 'HALCYON5', 'SYNERGY', 'SYNERGY2', 'SYNERGY3']

In [34]:
print(df.columns)

Index(['ds', 'equipo', 'y', 'capacidad', 'tipo_dia', 'novedad'], dtype='object')

In [35]:
print(df.shape)
print(df.head(5))

(13131, 6)
           ds      equipo  y  capacidad tipo_dia novedad
0  2022-05-03  EDGE1_6107  0          0      NaN     NaN
9  2022-05-04  EDGE1_6107  0          0      NaN     NaN
18 2022-05-05  EDGE1_6107  0          0      NaN     NaN
27 2022-05-06  EDGE1_6107  0          0      NaN     NaN
36 2022-05-07  EDGE1_6107  0          0      NaN     NaN

# Test funciones del pipeline

In [36]:
path_raw = settings.DATA_DIR / "raw" / "SESIONES_RADIOTERAPIA_5MAY22-30ABR2026.xlsx"
print(path_raw)
path_output = settings.OUTPUT_PATH / "demanda" / "produccion_radioterapia.csv"
print(path_output)

/home/jorge/Projects/Radioterapia/data/raw/SESIONES_RADIOTERAPIA_5MAY22-30ABR2026.xlsx
/home/jorge/Projects/Radioterapia/data/processed/demanda/produccion_radioterapia.csv

In [37]:
crea_produccion.create_df_produccion_x_equipo(path_raw, path_output)

,ds,equipo,y,capacidad,festivo,fin_de_semana,control_de_calidad,falla,mantenimiento
0,2022-05-03,EDGE1_6107,59,70,False,False,False,False,False
1,2022-05-03,EDGE2_6137,59,70,False,False,False,False,False
2,2022-05-03,HALCYON,59,70,False,False,False,False,False
3,2022-05-03,HALCYON3,41,65,False,False,False,False,False
4,2022-05-03,HALCYON4,41,65,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
13126,2026-04-30,HALCYON4,0,0,True,False,False,False,False
13127,2026-04-30,HALCYON5,0,0,True,False,False,False,False
13128,2026-04-30,SYNERGY,0,0,False,False,False,False,False
13129,2026-04-30,SYNERGY2,13,47,False,False,False,False,False
13130,2026-04-30,SYNERGY3,0,0,False,False,False,False,False

In [38]:
produccion_path = settings.OUTPUT_PATH / "demanda" / "produccion_radioterapia.csv"
print(produccion_path)
df_produccion = pd.read_csv(produccion_path)

/home/jorge/Projects/Radioterapia/data/processed/demanda/produccion_radioterapia.csv

In [39]:
df_produccion1 = df_produccion.copy()

In [40]:
print(df_produccion1.shape)

(13131, 9)

In [41]:
print(df_produccion1.head(4))

           ds      equipo   y  capacidad  festivo  fin_de_semana  \
0  2022-05-03  EDGE1_6107  59         70    False          False
1  2022-05-03  EDGE2_6137  59         70    False          False
2  2022-05-03     HALCYON  59         70    False          False
3  2022-05-03    HALCYON3  41         65    False          False

   control_de_calidad  falla  mantenimiento
0               False  False          False
1               False  False          False
2               False  False          False
3               False  False          False

In [42]:
demanda_diaria1 = df_produccion1.groupby("ds", as_index = False).agg(
    y = ("y", "sum"),
    capacidad = ("capacidad", "sum"),
    festivo = ("festivo", lambda x: x.mode()[0]),
    fin_de_semana = ("fin_de_semana", lambda x: x.mode()[0]),
    #laboral = ("laboral", lambda x: x.mode()[0]),
    control_de_calidad = ("control_de_calidad", lambda x: x.mode()[0]),
    falla = ("falla", lambda x: x.mode()[0]),
    mantenimiento = ("mantenimiento", lambda x: x.mode()[0]),
    #ninguna = ("ninguna", lambda x: x.mode()[0]),
)
print(demanda_diaria1.head(4))

           ds    y  capacidad  festivo  fin_de_semana  control_de_calidad  \
0  2022-05-03  407        564    False          False               False
1  2022-05-04  443        564    False          False               False
2  2022-05-05  451        564    False          False               False
3  2022-05-06  379        564    False          False               False

   falla  mantenimiento
0  False          False
1  False          False
2  False          False
3  False          False

In [43]:
df_produccion = extract.read_produccion(produccion_path)
print(df_produccion)

              ds      equipo   y  capacidad  festivo  fin_de_semana  \
0     2022-05-03  EDGE1_6107  59         70    False          False
1     2022-05-03  EDGE2_6137  59         70    False          False
2     2022-05-03     HALCYON  59         70    False          False
3     2022-05-03    HALCYON3  41         65    False          False
4     2022-05-03    HALCYON4  41         65    False          False
...          ...         ...  ..        ...      ...            ...
13126 2026-04-30    HALCYON4   0          0     True          False
13127 2026-04-30    HALCYON5   0          0     True          False
13128 2026-04-30     SYNERGY   0          0    False          False
13129 2026-04-30    SYNERGY2  13         47    False          False
13130 2026-04-30    SYNERGY3   0          0    False          False

       control_de_calidad  falla  mantenimiento
0                   False  False          False
1                   False  False          False
2                   False  False          False
3                   False  False          False
4                   False  False          False
...                   ...    ...            ...
13126               False  False          False
13127               False  False          False
13128               False  False          False
13129               False  False          False
13130               False  False          False

[13131 rows x 9 columns]

In [44]:
path_demanda_diaria = extract.get_demanda_diaria(df_produccion)

In [45]:
print(path_demanda_diaria)

/home/jorge/Projects/Radioterapia/data/processed/demanda/demanda_diaria_total.csv

In [46]:
path_demanda_hist = extract.get_demanda_hist_equipment(df_produccion)

In [47]:
print(path_demanda_hist)

/home/jorge/Projects/Radioterapia/data/processed/demanda/demanda_diaria_x_equipo.csv

In [48]:
print(settings.days_to_forecast)

30

In [49]:
os.makedirs(os.path.dirname(os.path.join(settings.OUTPUT_PATH, "demanda", "train")),exist_ok = True)
os.makedirs(os.path.dirname(os.path.join(settings.OUTPUT_PATH, "demanda", "test")), exist_ok = True)
os.makedirs(os.path.dirname(os.path.join(settings.OUTPUT_PATH, "demanda", "validation")), exist_ok = True)
path_train = os.path.join(settings.OUTPUT_PATH, "demanda", "train")
path_test = os.path.join(settings.OUTPUT_PATH, "demanda", "test")
path_val = os.path.join(settings.OUTPUT_PATH, "demanda", "validation")


path_demanda_hist = extract.get_demanda_hist_equipment(df_produccion)
df_hist = pd.read_csv(path_demanda_hist)
df_total = pd.read_csv(path_demanda_diaria)

In [50]:
print(df_hist.head(5))

           ds      equipo   y  capacidad  festivo  fin_de_semana  \
0  2022-05-03  EDGE1_6107  59         70    False          False
1  2022-05-03  EDGE2_6137  59         70    False          False
2  2022-05-03     HALCYON  59         70    False          False
3  2022-05-03    HALCYON3  41         65    False          False
4  2022-05-03    HALCYON4  41         65    False          False

   control_de_calidad  falla  mantenimiento
0               False  False          False
1               False  False          False
2               False  False          False
3               False  False          False
4               False  False          False

In [51]:
train,val,test,train_dates,val_dates,test_dates = filtra.train_val_test(df_hist, settings.days_to_forecast*2)

In [52]:
print(train.head(1))

           ds      equipo   y  capacidad  festivo  fin_de_semana  \
0  2022-05-03  EDGE1_6107  59         70    False          False

   control_de_calidad  falla  mantenimiento
0               False  False          False

In [53]:
print(val.head(1))

               ds      equipo  y  capacidad  festivo  fin_de_semana  \
12051  2026-01-01  EDGE1_6107  0          0     True          False

       control_de_calidad  falla  mantenimiento
12051               False  False          False

In [54]:
print(test.head(1))

               ds      equipo   y  capacidad  festivo  fin_de_semana  \
12591  2026-03-02  EDGE1_6107  18         21    False          False

       control_de_calidad  falla  mantenimiento
12591               False  False          False

In [55]:
print(path_train)

/home/jorge/Projects/Radioterapia/data/processed/demanda/train

In [56]:



train.to_csv(os.path.join(path_train,"train_demand_csv"), index = False)
np.savetxt(os.path.join(path_train,"train_dates.csv"), train_dates.astype(str), 
           delimiter = ",",
          fmt = "%s")


test.to_csv(os.path.join(path_test,"test_demand.csv"), index = False)
pd.Series(test_dates, name="ds").to_csv(os.path.join(path_val,"test_dates.csv"), 
                                                    index = False)

val.to_csv(os.path.join(path_val, "validation_demand.csv"), index = False)
pd.Series(val_dates, name="ds").to_csv(os.path.join(path_val,"val_dates.csv"), 
                                                    index = False)

In [57]:
print(type(train_dates))

<class 'numpy.ndarray'>

In [58]:
train, val, test, train_dates, val_dates, test_dates = filtra.train_val_test(df_total,60)

In [59]:
print(len(train))
print(len(val))
print(len(test))
print(type(train_dates))

1339
60
60
<class 'numpy.ndarray'>

In [60]:
print(train)

              ds    y  capacidad  festivo  fin_de_semana  control_de_calidad  \
0     2022-05-03  407        564    False          False               False
1     2022-05-04  443        564    False          False               False
2     2022-05-05  451        564    False          False               False
3     2022-05-06  379        564    False          False               False
4     2022-05-07    0          0    False          False               False
...          ...  ...        ...      ...            ...                 ...
1334  2025-12-27    0          0    False           True               False
1335  2025-12-28    0          0    False           True               False
1336  2025-12-29  173        352    False          False               False
1337  2025-12-30  166        352    False          False               False
1338  2025-12-31  142        352    False          False               False

      falla  mantenimiento
0     False          False
1     False          False
2     False          False
3     False          False
4     False          False
...     ...            ...
1334  False          False
1335  False          False
1336  False          False
1337  False          False
1338  False          False

[1339 rows x 8 columns]

## Fit final models

In [61]:
param_grid = {
    "changepoint_prior_scale": [0.01, 0.1, 0.5],
    "seasonality_prior_scale": [1, 5, 10] }

In [62]:
regressors = [c for c in train.columns if c not in ['ds','y','equipo']]

In [63]:
print(regressors)

['capacidad', 'festivo', 'fin_de_semana', 'control_de_calidad', 'falla', 'mantenimiento']

In [64]:
train = pd.read_csv(settings.DATA_DIR / "processed"/ "demanda" / "train"/ "train_demand.csv")

In [65]:
print(train.columns)

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

In [66]:
best_params = fcProphet.tune_total(train, val, regressors, param_grid)

06:25:06 - cmdstanpy - INFO - Chain [1] start processing
06:25:07 - cmdstanpy - INFO - Chain [1] done processing
06:25:07 - cmdstanpy - INFO - Chain [1] start processing
06:25:07 - cmdstanpy - INFO - Chain [1] done processing
06:25:07 - cmdstanpy - INFO - Chain [1] start processing
06:25:08 - cmdstanpy - INFO - Chain [1] done processing
06:25:08 - cmdstanpy - INFO - Chain [1] start processing
06:25:08 - cmdstanpy - INFO - Chain [1] done processing
06:25:09 - cmdstanpy - INFO - Chain [1] start processing
06:25:09 - cmdstanpy - INFO - Chain [1] done processing
06:25:10 - cmdstanpy - INFO - Chain [1] start processing
06:25:10 - cmdstanpy - INFO - Chain [1] done processing
06:25:10 - cmdstanpy - INFO - Chain [1] start processing
06:25:11 - cmdstanpy - INFO - Chain [1] done processing
06:25:11 - cmdstanpy - INFO - Chain [1] start processing
06:25:12 - cmdstanpy - INFO - Chain [1] done processing
06:25:12 - cmdstanpy - INFO - Chain [1] start processing
06:25:13 - cmdstanpy - INFO - Chain [1] done processing

In [67]:
train_full = df_hist[df_hist["ds"].isin(np.concatenate([train_dates, val_dates]))]
test = df_hist[df_hist["ds"].isin(test_dates)]

In [68]:
print(train_full.columns)

Index(['ds', 'equipo', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

In [69]:
models, residuals, results = fcProphet.bottom_up_models(train_full, best_params, regressors, equipos)

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:18 - cmdstanpy - INFO - Chain [1] start processing
06:25:18 - cmdstanpy - INFO - Chain [1] done processing
06:25:19 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:19 - cmdstanpy - INFO - Chain [1] done processing
06:25:19 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:20 - cmdstanpy - INFO - Chain [1] done processing
06:25:20 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:20 - cmdstanpy - INFO - Chain [1] done processing
06:25:21 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:21 - cmdstanpy - INFO - Chain [1] done processing
06:25:22 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:22 - cmdstanpy - INFO - Chain [1] done processing
06:25:22 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:22 - cmdstanpy - INFO - Chain [1] done processing
06:25:23 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:23 - cmdstanpy - INFO - Chain [1] done processing
06:25:24 - cmdstanpy - INFO - Chain [1] start processing

Index(['ds', 'y', 'capacidad', 'festivo', 'fin_de_semana',
       'control_de_calidad', 'falla', 'mantenimiento'],
      dtype='object')

06:25:24 - cmdstanpy - INFO - Chain [1] done processing

In [70]:
print(models)

{'EDGE1_6107': <prophet.forecaster.Prophet object at 0x7d85833cb4c0>, 'EDGE2_6137': <prophet.forecaster.Prophet object at 0x7d8582fb3970>, 'HALCYON': <prophet.forecaster.Prophet object at 0x7d8582fb1270>, 'HALCYON3': <prophet.forecaster.Prophet object at 0x7d8582fdeef0>, 'HALCYON4': <prophet.forecaster.Prophet object at 0x7d8582fb6110>, 'HALCYON5': <prophet.forecaster.Prophet object at 0x7d8582f73460>, 'SYNERGY': <prophet.forecaster.Prophet object at 0x7d8582f72650>, 'SYNERGY2': <prophet.forecaster.Prophet object at 0x7d8582fb4190>, 'SYNERGY3': <prophet.forecaster.Prophet object at 0x7d8582d11b40>}

In [71]:
print(residuals)
print(len(residuals))

[array([-1.08374661,  3.01623304,  2.70280319, ..., -5.37524474,
       -1.6604827 , -1.82877635], shape=(1399,)), array([-2.31092667,  2.29476154,  2.14146716, ...,  2.56435759,
       -5.9463928 , -6.20150924], shape=(1399,)), array([0.36142298, 4.49140245, 4.46078705, ..., 6.79808219, 5.1296372 ,
       4.93106673], shape=(1399,)), array([-10.16120538,  -5.67451237,  -4.73319939, ...,   9.06600545,
         3.11187822,   2.93166522], shape=(1399,)), array([-7.76310574, -3.92248678, -2.83259289, ...,  8.05391106,
       -1.74031642, -1.69208505], shape=(1399,)), array([ -9.40261403,  -4.56328828,  -3.42571099, ..., -16.93092113,
         1.1162593 ,   1.04569826], shape=(1399,)), array([-9.93433373, -5.33945487, -3.89370249, ...,  2.93513953,
        0.62731087,  0.56844096], shape=(1399,)), array([-4.69983008,  0.11792438,  2.4378011 , ..., -1.62856442,
        0.74641916,  0.7161795 ], shape=(1399,)), array([ -0.31127053,  -0.85331951,   3.84884038, ..., -13.64700725,
         4.23674989,   4.12407801], shape=(1399,))]
9

In [72]:
print(results["residual"])
print(results["residual"].shape)

0        -1.083747
1         3.016233
2         2.702803
3        -4.883727
4        -5.772648
           ...
12586    -5.093952
12587    -3.347794
12588   -13.647007
12589     0.000000
12590     0.000000
Name: residual, Length: 12591, dtype: float64
(12591,)

In [74]:
residual_m = np.array(residuals)
residual_flat = residual_m.flatten()

compare_residuals = pd.DataFrame({"residuals": residual_flat,
"results_residuals": results["residual"].values
})
compare_residuals["residuals_diff"] = compare_residuals["residuals"]-compare_residuals["results_residuals"]
print(compare_residuals["residuals_diff"].sum())
print(compare_residuals)

8003.409987072195
       residuals  results_residuals  residuals_diff
0      -1.083747          -1.083747        0.000000
1       3.016233           3.016233        0.000000
2       2.702803           2.702803        0.000000
3      -4.883727          -4.883727        0.000000
4      -5.772648          -5.772648        0.000000
...          ...                ...             ...
12586  -5.093952          -5.093952        0.000000
12587  -3.347794          -3.347794        0.000000
12588 -13.647007         -13.647007        0.000000
12589   4.236750           0.000000        4.236750
12590   4.124078           0.000000        4.124078

[12591 rows x 3 columns]

In [75]:
print(results)

               ds      equipo  festivo  fin_de_semana  control_de_calidad  \
0      2022-05-03  EDGE1_6107    False          False               False
1      2022-05-04  EDGE1_6107    False          False               False
2      2022-05-05  EDGE1_6107    False          False               False
3      2022-05-06  EDGE1_6107    False          False               False
4      2022-05-07  EDGE1_6107    False          False               False
...           ...         ...      ...            ...                 ...
12586  2026-02-25    SYNERGY3    False          False               False
12587  2026-02-26    SYNERGY3    False          False               False
12588  2026-02-27    SYNERGY3    False          False               False
12589  2026-02-28    SYNERGY3    False           True               False
12590  2026-03-01    SYNERGY3    False           True               False

       falla  mantenimiento  capacidad   y       yhat   residual
0      False          False         70  59  60.083747  -1.083747
1      False          False         70  64  60.983767   3.016233
2      False          False         70  63  60.297197   2.702803
3      False          False         70  55  59.883727  -4.883727
4      False          False          0   0   5.772648  -5.772648
...      ...            ...        ...  ..        ...        ...
12586  False          False         30   9  14.093952  -5.093952
12587  False          False         30  11  14.347794  -3.347794
12588  False          False         30   1  14.647007 -13.647007
12589  False          False          0   0   0.000000   0.000000
12590  False          False          0   0   0.000000   0.000000

[12591 rows x 11 columns]

## Covariance Matrices and Standard Mint

In [76]:

pred_total_train, train_total_fc_and_pred, res_total, m_total = fcProphet.top_down_total(train_full,best_params ,regressors)

06:25:46 - cmdstanpy - INFO - Chain [1] start processing
06:25:47 - cmdstanpy - INFO - Chain [1] done processing

In [77]:
print(m_total)

<prophet.forecaster.Prophet object at 0x7d85831f7eb0>

In [78]:
print(len(res_total))
print(residuals)

1399
[array([-1.08374661,  3.01623304,  2.70280319, ..., -5.37524474,
       -1.6604827 , -1.82877635], shape=(1399,)), array([-2.31092667,  2.29476154,  2.14146716, ...,  2.56435759,
       -5.9463928 , -6.20150924], shape=(1399,)), array([0.36142298, 4.49140245, 4.46078705, ..., 6.79808219, 5.1296372 ,
       4.93106673], shape=(1399,)), array([-10.16120538,  -5.67451237,  -4.73319939, ...,   9.06600545,
         3.11187822,   2.93166522], shape=(1399,)), array([-7.76310574, -3.92248678, -2.83259289, ...,  8.05391106,
       -1.74031642, -1.69208505], shape=(1399,)), array([ -9.40261403,  -4.56328828,  -3.42571099, ..., -16.93092113,
         1.1162593 ,   1.04569826], shape=(1399,)), array([-9.93433373, -5.33945487, -3.89370249, ...,  2.93513953,
        0.62731087,  0.56844096], shape=(1399,)), array([-4.69983008,  0.11792438,  2.4378011 , ..., -1.62856442,
        0.74641916,  0.7161795 ], shape=(1399,)), array([ -0.31127053,  -0.85331951,   3.84884038, ..., -13.64700725,
         4.23674989,   4.12407801], shape=(1399,))]

In [79]:
residual_matrix = np.vstack([res_total] + residuals)
print(residual_matrix.shape)

(10, 1399)

In [80]:
print(pred_total_train)
print(pred_total_train.shape)

             ds       trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
0    2022-05-03  289.333875  408.965811  496.310304   289.333875   289.333875
1    2022-05-04  289.309516  412.791528  495.383436   289.309516   289.309516
2    2022-05-05  289.285157  406.877959  493.035453   289.285157   289.285157
3    2022-05-06  289.260798  396.935070  481.751544   289.260798   289.260798
4    2022-05-07  289.236439  -27.285973   59.440678   289.236439   289.236439
...         ...         ...         ...         ...          ...          ...
1394 2026-02-25  193.401114  162.857261  246.073286   193.401114   193.401114
1395 2026-02-26  193.544662  114.444870  198.229037   193.544662   193.544662
1396 2026-02-27  193.688211  150.684847  236.063359   193.688211   193.688211
1397 2026-02-28  193.831760   -8.606460   72.871864   193.831760   193.831760
1398 2026-03-01  193.975309   -9.593913   76.180257   193.975309   193.975309

      additive_terms  additive_terms_lower  additive_terms_upper   capacidad  \
0         163.637644            163.637644            163.637644  180.816094
1         165.271688            165.271688            165.271688  180.816094
2         160.835747            160.835747            160.835747  180.816094
3         148.961377            148.961377            148.961377  180.816094
4        -277.396995           -277.396995           -277.396995 -262.573658
...              ...                   ...                   ...         ...
1394       10.659777             10.659777             10.659777   41.667182
1395      -36.922989            -36.922989            -36.922989   -9.432701
1396       -1.833743             -1.833743             -1.833743   41.667182
1397     -161.550291           -161.550291           -161.550291 -225.624512
1398     -160.572070           -160.572070           -160.572070 -225.624512

      ...     weekly  weekly_lower  weekly_upper    yearly  yearly_lower  \
0     ...  34.098588     34.098588     34.098588  7.317521      7.317521
1     ...  36.965064     36.965064     36.965064  6.085089      6.085089
2     ...  33.608181     33.608181     33.608181  5.006031      5.006031
3     ...  22.646880     22.646880     22.646880  4.092961      4.092961
4     ... -78.096610    -78.096610    -78.096610  3.354604      3.354604
...   ...        ...           ...           ...       ...           ...
1394  ...  36.965064     36.965064     36.965064 -9.377911     -9.377911
1395  ...  33.608181     33.608181     33.608181 -8.473587     -8.473587
1396  ...  22.646880     22.646880     22.646880 -7.553247     -7.553247
1397  ... -78.096610    -78.096610    -78.096610 -6.632759     -6.632759
1398  ... -78.023185    -78.023185    -78.023185 -5.727962     -5.727962

      yearly_upper  multiplicative_terms  multiplicative_terms_lower  \
0         7.317521                   0.0                         0.0
1         6.085089                   0.0                         0.0
2         5.006031                   0.0                         0.0
3         4.092961                   0.0                         0.0
4         3.354604                   0.0                         0.0
...            ...                   ...                         ...
1394     -9.377911                   0.0                         0.0
1395     -8.473587                   0.0                         0.0
1396     -7.553247                   0.0                         0.0
1397     -6.632759                   0.0                         0.0
1398     -5.727962                   0.0                         0.0

      multiplicative_terms_upper        yhat
0                            0.0  452.971519
1                            0.0  454.581204
2                            0.0  450.120904
3                            0.0  438.222175
4                            0.0   11.839444
...                          ...         ...
1394                         0.0  204.060891
1395                         0.0  156.621674
1396                         0.0  191.854469
1397                         0.0   32.281469
1398                         0.0   33.403239

[1399 rows x 40 columns]
(1399, 40)

In [81]:
print(train_total_fc_and_pred)
print(train_total_fc_and_pred.shape)
print(type(train_total_fc_and_pred))

             ds    y        yhat  residuals
0    2022-05-03  407  452.971519 -45.971519
1    2022-05-04  443  454.581204 -11.581204
2    2022-05-05  451  450.120904   0.879096
3    2022-05-06  379  438.222175 -59.222175
4    2022-05-07    0   11.839444 -11.839444
...         ...  ...         ...        ...
1394 2026-02-25  209  204.060891   4.939109
1395 2026-02-26  205  156.621674  48.378326
1396 2026-02-27  186  191.854469  -5.854469
1397 2026-02-28   13   32.281469 -19.281469
1398 2026-03-01   13   33.403239 -20.403239

[1399 rows x 4 columns]
(1399, 4)
<class 'pandas.core.frame.DataFrame'>

In [82]:
print(pred_total_train.head(4))
print(pred_total_train.shape)
print(type(pred_total_train))

          ds       trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
0 2022-05-03  289.333875  408.965811  496.310304   289.333875   289.333875
1 2022-05-04  289.309516  412.791528  495.383436   289.309516   289.309516
2 2022-05-05  289.285157  406.877959  493.035453   289.285157   289.285157
3 2022-05-06  289.260798  396.935070  481.751544   289.260798   289.260798

   additive_terms  additive_terms_lower  additive_terms_upper   capacidad  \
0      163.637644            163.637644            163.637644  180.816094
1      165.271688            165.271688            165.271688  180.816094
2      160.835747            160.835747            160.835747  180.816094
3      148.961377            148.961377            148.961377  180.816094

   ...     weekly  weekly_lower  weekly_upper    yearly  yearly_lower  \
0  ...  34.098588     34.098588     34.098588  7.317521      7.317521
1  ...  36.965064     36.965064     36.965064  6.085089      6.085089
2  ...  33.608181     33.608181     33.608181  5.006031      5.006031
3  ...  22.646880     22.646880     22.646880  4.092961      4.092961

   yearly_upper  multiplicative_terms  multiplicative_terms_lower  \
0      7.317521                   0.0                         0.0
1      6.085089                   0.0                         0.0
2      5.006031                   0.0                         0.0
3      4.092961                   0.0                         0.0

   multiplicative_terms_upper        yhat
0                         0.0  452.971519
1                         0.0  454.581204
2                         0.0  450.120904
3                         0.0  438.222175

[4 rows x 40 columns]
(1399, 40)
<class 'pandas.core.frame.DataFrame'>

In [83]:
print(res_total)
print(res_total.shape)
print(type(res_total))

[-45.97151888 -11.58120428   0.87909577 ...  -5.85446854 -19.28146869
 -20.40323909]
(1399,)
<class 'numpy.ndarray'>

In [84]:
print(m_total)
print(type(m_total))

<prophet.forecaster.Prophet object at 0x7d85831f7eb0>
<class 'prophet.forecaster.Prophet'>

In [85]:
results

,ds,equipo,festivo,fin_de_semana,control_de_calidad,falla,mantenimiento,capacidad,y,yhat,residual
0,2022-05-03,EDGE1_6107,False,False,False,False,False,70,59,60.083747,-1.083747
1,2022-05-04,EDGE1_6107,False,False,False,False,False,70,64,60.983767,3.016233
2,2022-05-05,EDGE1_6107,False,False,False,False,False,70,63,60.297197,2.702803
3,2022-05-06,EDGE1_6107,False,False,False,False,False,70,55,59.883727,-4.883727
4,2022-05-07,EDGE1_6107,False,False,False,False,False,0,0,5.772648,-5.772648
...,...,...,...,...,...,...,...,...,...,...,...
12586,2026-02-25,SYNERGY3,False,False,False,False,False,30,9,14.093952,-5.093952
12587,2026-02-26,SYNERGY3,False,False,False,False,False,30,11,14.347794,-3.347794
12588,2026-02-27,SYNERGY3,False,False,False,False,False,30,1,14.647007,-13.647007
12589,2026-02-28,SYNERGY3,False,True,False,False,False,0,0,0.000000,0.000000
12590,2026-03-01,SYNERGY3,False,True,False,False,False,0,0,0.000000,0.000000

In [86]:
results.pivot(index = "ds", columns = "equipo", values = "residual")

equipo,EDGE1_6107,EDGE2_6137,HALCYON,HALCYON3,HALCYON4,HALCYON5,SYNERGY,SYNERGY2,SYNERGY3
ds,,,,,,,,,
2022-05-03,-1.083747,-2.310927,0.361423,-10.161205,-7.763106,-9.402614,-9.934334,-4.699830,-0.311271
2022-05-04,3.016233,2.294762,4.491402,-5.674512,-3.922487,-4.563288,-5.339455,0.117924,-0.853320
2022-05-05,2.702803,2.141467,4.460787,-4.733199,-2.832593,-3.425711,-3.893702,2.437801,3.848840
2022-05-06,-4.883727,-5.992408,-1.929453,-5.814438,-3.810004,-3.865575,-5.119132,1.609211,-30.500409
2022-05-07,-5.772648,-9.044375,-9.876124,-1.817219,-0.376726,-1.921141,-5.002133,-9.777074,-11.068120
...,...,...,...,...,...,...,...,...,...
2026-02-25,-1.784467,4.700322,11.128180,6.060513,13.932280,-22.375436,0.000000,-2.847330,-5.093952
2026-02-26,-4.452796,3.113827,16.625429,16.572513,24.088383,0.000000,0.000000,-2.667047,-3.347794
2026-02-27,-5.375245,2.564358,6.798082,9.066005,8.053911,-16.930921,0.000000,-1.628564,-13.647007
2026-02-28,-1.660483,-5.946393,0.000000,0.000000,-1.740316,0.000000,0.000000,0.746419,0.000000
2026-03-01,-1.828776,-6.201509,0.000000,0.000000,-1.692085,0.000000,0.000000,0.716179,0.000000

In [87]:
print(equipos)
residuals_matrix,residuals_df = fcProphet.cal_residual_matrix(res_total, residuals, equipos)

['EDGE1_6107', 'EDGE2_6137', 'HALCYON', 'HALCYON3', 'HALCYON4', 'HALCYON5', 'SYNERGY', 'SYNERGY2', 'SYNERGY3']

In [88]:
print(residuals_df.shape)

(10, 1399)

In [89]:
print(residuals_df)
print(type(residuals_df))
np.cov(residuals_df).shape

                 0          1         2          3          4          5     \
total      -45.971519 -11.581204  0.879096 -59.222175 -11.839444 -11.329637
EDGE1_6107  -1.083747   3.016233  2.702803  -4.883727  -5.772648  -5.655578
EDGE2_6137  -2.310927   2.294762  2.141467  -5.992408  -9.044375  -8.936298
HALCYON      0.361423   4.491402  4.460787  -1.929453  -9.876124  -9.726857
HALCYON3   -10.161205  -5.674512 -4.733199  -5.814438  -1.817219  -1.598829
HALCYON4    -7.763106  -3.922487 -2.832593  -3.810004  -0.376726  -0.435253
HALCYON5    -9.402614  -4.563288 -3.425711  -3.865575  -1.921141  -1.875803
SYNERGY     -9.934334  -5.339455 -3.893702  -5.119132  -5.002133  -4.848819
SYNERGY2    -4.699830   0.117924  2.437801   1.609211  -9.777074  -9.689878
SYNERGY3    -0.311271  -0.853320  3.848840 -30.500409 -11.068120 -11.238535

                6         7         8          9     ...       1389  \
total      -6.627527  7.300485  8.488658 -33.260894  ... -17.299913
EDGE1_6107 -0.139989  1.864626  1.863127   2.440964  ...   2.966570
EDGE2_6137 -0.956083  0.747254  1.139276   1.770361  ...  -3.271925
HALCYON     2.667255  3.613610  3.610958   4.447388  ...  -0.389106
HALCYON3   -3.811112 -1.406242 -1.094979 -12.347386  ...  -9.284047
HALCYON4   -2.434945 -0.832318 -1.237439 -12.369737  ...  -1.247744
HALCYON5   -2.763679 -1.805765 -1.181422 -12.263374  ...  -2.394507
SYNERGY    -3.487510 -1.681561 -1.237461 -11.942610  ...   3.486726
SYNERGY2    2.496238  5.102641  6.804191   4.994138  ...  -1.696954
SYNERGY3    1.987427  3.492347  2.075586   2.927970  ...  -4.442506

                 1390       1391       1392       1393       1394       1395  \
total      -12.367918 -13.281310 -26.825680  -1.178005   4.939109  48.378326
EDGE1_6107  -0.331299  -0.529782  -2.233142  -0.515199  -1.784467  -4.452796
EDGE2_6137  -4.560743  -4.714943   3.078647   6.539166   4.700322   3.113827
HALCYON      6.905199   6.631048   1.942166   1.497946  11.128180  16.625429
HALCYON3     3.883160   3.814826  -6.138418   4.000864   6.060513  16.572513
HALCYON4    -2.058732  -2.027029 -17.605423 -14.845989  13.932280  24.088383
HALCYON5     0.815874   0.917907   6.875197   7.912910 -22.375436  21.596614
SYNERGY      1.166746   1.082083   1.406853   1.016638   1.287737   1.433487
SYNERGY2     0.695384   0.693531  -2.076524  -2.519493  -2.847330  -2.667047
SYNERGY3     5.386667   5.192440  -0.734909  -4.588774  -5.093952  -3.347794

                 1396       1397       1398
total       -5.854469 -19.281469 -20.403239
EDGE1_6107  -5.375245  -1.660483  -1.828776
EDGE2_6137   2.564358  -5.946393  -6.201509
HALCYON      6.798082   5.129637   4.931067
HALCYON3     9.066005   3.111878   2.931665
HALCYON4     8.053911  -1.740316  -1.692085
HALCYON5   -16.930921   1.116259   1.045698
SYNERGY      2.935140   0.627311   0.568441
SYNERGY2    -1.628564   0.746419   0.716179
SYNERGY3   -13.647007   4.236750   4.124078

[10 rows x 1399 columns]
<class 'pandas.core.frame.DataFrame'>

(10, 10)

In [90]:
W, lw, W_shrink = fcProphet.compute_covariance_matrices(residuals_df)

In [91]:
S = fcProphet.summing_matrix(equipos)

In [92]:
from numpy.linalg import inv
print(S.T.shape) 
print(S.T)
print(W.shape)

(9, 10)
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
(10, 10)

In [93]:
print(W.shape)
print(S.shape)
print(test.head(5))

(10, 10)
(10, 9)
               ds      equipo   y  capacidad  festivo  fin_de_semana  \
12591  2026-03-02  EDGE1_6107  18         21    False          False
12592  2026-03-02  EDGE2_6137  13         36    False          False
12593  2026-03-02     HALCYON  36         55    False          False
12594  2026-03-02    HALCYON3  26         65    False          False
12595  2026-03-02    HALCYON4  42         65    False          False

       control_de_calidad  falla  mantenimiento
12591               False  False          False
12592               False  False          False
12593               False  False          False
12594               False  False          False
12595               False  False          False

In [94]:
test[test["equipo"] == equipos[0]] [["ds"]+regressors]

,ds,capacidad,festivo,fin_de_semana,control_de_calidad,falla,mantenimiento
12591,2026-03-02,21,False,False,False,False,False
12600,2026-03-03,21,False,False,False,False,False
12609,2026-03-04,21,False,False,False,False,False
12618,2026-03-05,21,False,False,False,False,False
12627,2026-03-06,21,False,False,False,False,False
12636,2026-03-07,0,False,True,False,False,False
12645,2026-03-08,0,False,True,False,False,False
12654,2026-03-09,21,False,False,False,False,False
12663,2026-03-10,21,False,False,False,False,False
12672,2026-03-11,21,False,False,False,False,False
12681,2026-03-12,21,False,False,False,False,False
12690,2026-03-13,21,False,False,False,False,False
12699,2026-03-14,0,False,True,False,False,False
12708,2026-03-15,0,False,True,False,False,False
12717,2026-03-16,21,False,False,False,False,False
12726,2026-03-17,21,False,False,False,False,False
12735,2026-03-18,21,False,False,False,False,False
12744,2026-03-19,21,False,False,False,False,False
12753,2026-03-20,21,False,False,False,False,False
12762,2026-03-21,0,False,True,False,False,False
12771,2026-03-22,0,False,True,False,False,False
12780,2026-03-23,21,False,False,True,False,False
12789,2026-03-24,21,False,False,False,False,False
12798,2026-03-25,21,False,False,False,False,False
12807,2026-03-26,21,False,False,False,False,False
12816,2026-03-27,21,False,False,False,False,False
12825,2026-03-28,0,False,True,False,False,False
12834,2026-03-29,0,False,True,False,False,False
12843,2026-03-30,21,False,False,False,False,False
12852,2026-03-31,21,False,False,False,False,False
12861,2026-04-01,21,False,False,False,False,False
12870,2026-04-02,21,False,False,False,False,False
12879,2026-04-03,0,True,False,False,False,False
12888,2026-04-04,0,False,True,False,False,False
12897,2026-04-05,0,False,True,False,False,False
12906,2026-04-06,21,False,False,False,False,False
12915,2026-04-07,21,False,False,False,False,False
12924,2026-04-08,21,False,False,False,False,False
12933,2026-04-09,21,False,False,False,False,False
12942,2026-04-10,21,False,False,False,False,False
12951,2026-04-11,0,False,True,False,False,False
12960,2026-04-12,0,False,True,False,False,False
12969,2026-04-13,21,False,False,False,False,False
12978,2026-04-14,21,False,False,False,False,False
12987,2026-04-15,21,False,False,False,False,False
12996,2026-04-16,21,False,False,False,False,False
13005,2026-04-17,21,False,False,True,False,False
13014,2026-04-18,0,False,True,False,False,False
13023,2026-04-19,0,False,True,False,False,False
13032,2026-04-20,21,False,False,False,False,False
13041,2026-04-21,21,False,False,False,False,False
13050,2026-04-22,21,False,False,False,False,False
13059,2026-04-23,21,False,False,False,False,False
13068,2026-04-24,21,False,False,False,False,False
13077,2026-04-25,0,False,True,False,False,False
13086,2026-04-26,0,False,True,False,False,False
13095,2026-04-27,21,False,False,False,False,False
13104,2026-04-28,21,False,False,False,False,False
13113,2026-04-29,21,False,False,False,False,False
13122,2026-04-30,0,True,False,False,False,False

In [95]:
test[test["equipo"] == equipos[0]]["y"].values

array([18, 11, 17, 12, 11,  0,  0, 12, 14, 13, 12,  9,  0,  0, 22, 16, 15,
       20, 14,  0,  0,  5, 14, 11, 12, 12,  0,  0, 26, 13, 13, 13,  0,  0,
        0, 14, 16, 13,  9,  8,  0,  0, 11,  8, 23, 10, 13,  0,  0,  8,  6,
        7, 10, 20,  0,  0, 20, 21, 20,  0])

In [96]:
results_test_df, Yhat, total_pred = fcProphet.fc_bottom_up_test(test_dates, test, m_total, models, equipos, regressors)

In [97]:
print(results_test_df.head(5))

           ds      equipo  festivo  fin_de_semana  control_de_calidad  falla  \
0  2026-03-02  EDGE1_6107    False          False               False  False
1  2026-03-03  EDGE1_6107    False          False               False  False
2  2026-03-04  EDGE1_6107    False          False               False  False
3  2026-03-05  EDGE1_6107    False          False               False  False
4  2026-03-06  EDGE1_6107    False          False               False  False

   mantenimiento  capacidad   y       yhat  residual
0          False         21  18  13.513211  4.486789
1          False         21  11  13.729597 -2.729597
2          False         21  17  14.916105  2.083895
3          False         21  12  14.485577 -2.485577
4          False         21  11  14.294469 -3.294469

In [98]:
print(Yhat)

[[ 1.91704542e+02  1.97973952e+02  2.06669493e+02  2.04156578e+02
   1.93960714e+02  3.85223712e+01  3.91874391e+01  2.02943130e+02
   2.07601065e+02  2.10799794e+02  2.07700937e+02  1.97988402e+02
   4.09601001e+01  4.11435818e+01  2.09405618e+02  2.08827652e+02
   2.11809147e+02  2.08607795e+02  1.98916074e+02  4.20370973e+01
   4.25000178e+01  2.06253926e+02  2.11121004e+02  2.14744467e+02
   2.12284417e+02  1.85853614e+02  1.77975406e+01  1.91902617e+01
   1.77486838e+02  1.97904212e+02  2.02436600e+02  2.00827340e+02
   4.14079188e+01  2.91933033e+01  3.11176899e+01  2.08268127e+02
   2.15349748e+02  2.15008587e+02  2.13255508e+02  2.08682856e+02
   4.07627154e+01  4.19763879e+01  2.13323216e+02  2.19352446e+02
   2.27642664e+02  2.20701744e+02  2.34361910e+02  4.42194814e+01
   4.38789183e+01  2.13652876e+02  2.18120834e+02  1.81653129e+02
   1.77125052e+02  2.04234572e+02  3.74443063e+01  3.60252011e+01
   2.04887093e+02  2.08625144e+02  2.09944090e+02  5.48154601e+01]
 [ 1.35132107e+01  1.37295971e+01  1.49161052e+01  1.44855774e+01
   1.42944689e+01  2.42414755e+00  2.45516434e+00  1.39939498e+01
   1.40589908e+01  1.50913218e+01  1.45067744e+01  1.41648470e+01
   2.14993289e+00  2.04551761e+00  1.34608039e+01  1.34168197e+01
   1.43568466e+01  1.36986112e+01  1.33031067e+01  1.25578094e+00
   1.14070442e+00  7.78521264e+00  1.25558330e+01  1.35490685e+01
   1.29632578e+01  1.26576003e+01  7.15349860e-01  7.18032622e-01
   1.22721131e+01  1.23951621e+01  1.35263614e+01  1.30787896e+01
   1.34033843e+00  1.09507148e+00  1.21741149e+00  1.28789836e+01
   1.30947962e+01  1.43018148e+01  1.39112981e+01  1.37777649e+01
   1.98032984e+00  2.09701437e+00  1.37314908e+01  1.38993102e+01
   1.50384498e+01  1.45616199e+01  9.54322793e+00  2.41049228e+00
   2.39804742e+00  1.38942766e+01  1.39176484e+01  1.49091593e+01
   1.42845703e+01  1.39032659e+01  1.84947404e+00  1.70645823e+00
   1.30831411e+01  1.30002141e+01  1.39005717e+01  1.63350152e+00]
 [ 1.87555151e+01  1.93440921e+01  2.02031867e+01  1.97801718e+01
   2.02902876e+01  7.46123230e+00  7.62039611e+00  2.00533027e+01
   2.04987224e+01  2.11963337e+01  2.05977845e+01  2.09230161e+01
   7.90472471e+00  7.87545696e+00  2.92611115e+01  2.03998848e+01
   2.09418340e+01  2.02077577e+01  2.04214173e+01  7.31868231e+00
   7.23453225e+00  1.94612802e+01  1.97434894e+01  2.03254641e+01
   1.96621722e+01  1.99754659e+01  6.99847855e+00  7.06269621e+00
   3.94020387e+00  1.99190532e+01  2.06901972e+01  2.02192336e+01
   8.03386541e+00  7.92734730e+00  8.16005003e+00  2.07035827e+01
   2.12931301e+01  2.21637644e+01  2.17616192e+01  2.23003523e+01
   9.50576839e+00  9.70309222e+00  2.21754585e+01  2.26590789e+01
   3.25261682e+01  2.28200464e+01  3.22987784e+01  1.01516355e+01
   1.01143242e+01  2.23400981e+01  2.25708085e+01  2.30492731e+01
   2.22302490e+01  1.94361227e+01  9.10403540e+00  8.86741725e+00
   2.09197105e+01  2.10065416e+01  2.13737504e+01  7.78972588e+00]
 [ 3.24806707e+01  3.37735423e+01  3.49565527e+01  3.42401121e+01
   3.28197283e+01 -4.62017087e+00 -4.71148037e+00  3.23980979e+01
   3.33830468e+01  3.42591776e+01  3.32438262e+01  3.15393696e+01
  -6.16312866e+00 -6.48933308e+00  1.20972053e+01  3.12404458e+01
   3.19957609e+01  3.09051305e+01  2.91730178e+01 -8.50853443e+00
  -8.76534968e+00  2.82592323e+01  2.92422250e+01  3.02000625e+01
   2.93487682e+01  2.78874922e+01 -9.49777274e+00 -9.43948871e+00
   2.36783480e+01  2.92262133e+01  3.05123755e+01  2.99791705e+01
  -7.98887769e+00 -8.28942711e+00 -7.98376712e+00  2.95801408e+01
   3.10676707e+01  3.24845047e+01  3.20370515e+01  3.09162025e+01
  -6.19876913e+00 -5.94536468e+00  3.15227517e+01  3.28738478e+01
   3.41173745e+01  3.34642736e+01  2.78770124e+01 -5.25869642e+00
  -5.27513076e+00  3.19138221e+01  3.29826373e+01 -5.08187587e+00
  -6.00554852e+00  3.14130553e+01 -6.19372737e+00 -6.42448865e+00
   3.05767540e+01  3.14871480e+01  3.23240636e+01 -5.50239271e+00]
 [ 3.31207517e+01  3.30650428e+01  3.30709146e+01  3.36044483e+01
   3.21351463e+01 -1.90861422e+00 -1.74845259e+00  1.91555509e+01
   3.41445932e+01  3.40699053e+01  3.45067406e+01  3.29275079e+01
  -1.23608471e+00 -1.20199410e+00  3.46803600e+01  3.44358739e+01
   3.42400986e+01  3.45654142e+01  3.28878975e+01 -1.35741373e+00
  -1.38558553e+00  3.44563248e+01  3.41949717e+01  3.40070011e+01
   3.43651829e+01  3.27452564e+01 -1.41880738e+00 -1.34385277e+00
   3.46206113e+01  3.44981712e+01  3.44618629e+01  3.49803944e+01
  -1.04101024e+00 -4.74709964e-01 -2.40621444e-01  3.58731061e+01
   3.58854533e+01  3.59651128e+01  3.65768309e+01  3.51884643e+01
   1.22645392e+00  1.46698053e+00  3.75543066e+01  3.75067088e+01
   3.74929824e+01  3.79787870e+01  2.99752880e+01  2.28659874e+00
   2.31687050e+00  3.81725706e+01  3.78763201e+01  3.76016946e+01
   3.78194561e+01  3.60044718e+01  1.59102345e+00  1.36377867e+00
   3.69759311e+01  3.64549211e+01  3.59787221e+01  1.45586443e+00]
 [ 3.92549110e+01  3.94818274e+01  3.96930022e+01  3.96143695e+01
   3.75651272e+01  1.36679735e+00  1.33526533e+00  3.89257199e+01
   3.91928035e+01  3.94581659e+01  3.94490300e+01  3.74856271e+01
   1.39019592e+00  1.47896814e+00  3.92070611e+01  3.96285905e+01
   4.00641973e+01  4.02396002e+01  2.33894542e+01  2.58423692e+00
   2.88651627e+00  4.08316307e+01  4.14699858e+01  4.21182246e+01
   4.24978603e+01  4.09228012e+01  5.20846173e+00  5.66387952e+00
   4.37367573e+01  4.44737383e+01  4.51881067e+01  4.55985184e+01
   7.19013734e+00  8.25621406e+00  8.62549135e+00  4.65720710e+01
   4.71433332e+01  4.76541267e+01  4.78254924e+01  4.59722503e+01
   9.91214149e+00  9.95794344e+00  4.75624753e+01  4.77788034e+01
   4.79278381e+01  3.26533549e+01  4.17875402e+01  9.12313315e+00
   8.84336919e+00  4.61467436e+01  4.60917685e+01  4.60042186e+01
   4.56156111e+01  4.32505560e+01  6.73567350e+00  6.39150343e+00
   4.36773282e+01  4.36512253e+01  4.36375425e+01  6.53893279e+00]
 [ 3.41751926e+01  3.53174407e+01  3.47838348e+01  3.49465337e+01
   3.26760460e+01 -2.18426743e-01 -8.85956396e-03  3.53355131e+01
   3.65844443e+01  3.61400173e+01  3.63742549e+01  2.05092951e+01
   1.30163949e+00  1.53435481e+00  3.68888041e+01  3.81368777e+01
   3.76830363e+01  3.79018279e+01  3.56667532e+01  2.79047643e+00
   3.00481082e+00  3.83444804e+01  3.95832093e+01  3.91269064e+01
   3.93511259e+01  3.71298909e+01  4.27587998e+00  4.52040516e+00
   2.67218733e+01  4.11784626e+01  4.07682353e+01  4.10397765e+01
   4.97561480e+00  6.05240272e+00  6.33179763e+00  2.85582155e+01
   2.98517032e+01  4.26136323e+01  4.28643178e+01  2.74732572e+01
   7.77479609e+00  7.97046304e+00  4.32660163e+01  4.44311421e+01
   4.38681180e+01  4.39494325e+01  2.83714429e+01  8.47124955e+00
   8.45366151e+00  4.35281679e+01  4.44685469e+01  4.36814277e+01
   4.35437980e+01  4.09318559e+01  7.66120442e+00  7.46681422e+00
   4.23867604e+01  4.31982813e+01  4.23109295e+01  8.21507524e+00]
 [-9.30939048e-01 -5.88357813e-01 -9.14679180e-01 -1.12069132e+00
  -2.68491917e+00 -4.39137143e-01 -4.38894545e-01 -8.53730507e-01
  -5.54418608e-01 -9.12322817e-01 -1.13584263e+00 -2.70140803e+00
  -4.39051271e-01 -4.02984563e-01 -7.61859000e-01 -3.86043654e-01
  -6.47005438e-01 -7.53766805e-01 -2.18390134e+00  2.30906056e-01
   4.34305195e-01  2.55057400e-01  8.19803348e-01  7.53740568e-01
   8.44232370e-01 -3.90113269e-01  2.21507681e+00  2.59947216e+00
   2.58790314e+00  3.30321696e+00  3.36704167e+00  3.56347808e+00
   2.40825583e+00  5.06332365e+00  5.46644103e+00  5.44109222e+00
   6.10937983e+00  6.09281325e+00  6.17601114e+00  4.87585399e+00
   7.35605655e+00  7.55672781e+00  7.30424011e+00  7.72406541e+00
   7.44149558e+00  7.24526719e+00  5.65662873e+00  7.84382211e+00
   7.75154807e+00  7.21073953e+00  7.35130297e+00  6.80274706e+00
   6.35772112e+00  4.54100346e+00  6.52391318e+00  6.25371683e+00
   5.56335509e+00  5.58415089e+00  4.94641863e+00  4.44299765e+00]
 [ 1.50930707e+01  1.55855397e+01  1.59724083e+01  1.58596708e+01
   1.48960168e+01  1.26017299e+01  1.27169779e+01  1.56138895e+01
   1.61949557e+01  1.66696248e+01  1.66421868e+01  1.57596963e+01
   1.35409100e+01  1.37246113e+01  1.66817171e+01  1.73137035e+01
   1.78292196e+01  1.78319839e+01  1.69687127e+01  1.47580567e+01
   1.49389180e+01  1.78825438e+01  1.84909334e+01  1.89734283e+01
   1.89345811e+01  1.80220537e+01  1.57555214e+01  1.58749566e+01
   1.87526894e+01  1.92917822e+01  1.97025902e+01  1.95906034e+01
   1.86043215e+01  1.62641396e+01  1.63106185e+01  1.91165369e+01
   1.95852637e+01  1.99273209e+01  1.97482344e+01  1.86964224e+01
   1.62920984e+01  1.62755638e+01  1.90192846e+01  1.94262908e+01
   1.97067680e+01  1.94659366e+01  1.83519676e+01  1.58849128e+01
   1.58050198e+01  1.84848293e+01  1.88275901e+01  1.90438611e+01
   1.87393957e+01  1.75630578e+01  1.50357443e+01  1.48986888e+01
   1.75255403e+01  1.78207548e+01  1.79961693e+01  1.76588539e+01]
 [ 1.10213310e+01  1.14581110e+01  3.52894787e+00  3.62554473e+00
   3.75859863e+00 -4.03917121e+00 -4.09745864e+00  2.59060209e+00
   2.86807420e+00  3.08110488e+00  3.04379959e+00  3.05956024e+00
  -4.83709201e+00 -4.97470084e+00  1.65408267e+00  1.89214377e+00
   2.08481690e+00  2.04480599e+00  2.07358640e+00 -5.79669284e+00
  -5.89730068e+00  7.76135809e-01  1.06338426e+00  1.30663210e+00
   1.31551876e+00 -5.53299120e+00 -2.74748642e+00 -2.82021769e+00
   1.54173203e+00  1.83347554e+00  2.06825575e+00  2.05564036e+00
   2.09475262e+00 -3.45545585e+00 -3.58337786e+00  7.15755960e-01
   9.39622523e-01  1.10436994e+00  1.02271686e+00  9.97078948e-01
  -4.61026844e+00 -4.78447561e+00 -5.17723229e-01 -3.09583862e-01
  -1.41557205e-01 -1.99058625e-01 -1.78366786e-01 -5.71651888e+00
  -5.79863572e+00 -1.41754690e+00 -1.07415230e+00 -7.51937058e-01
  -6.38919695e-01 -4.34540401e-01 -5.77947944e+00 -5.66289015e+00
  -1.08191920e+00 -5.41953453e-01 -3.10137107e-02  2.58421447e-01]]

In [99]:
Yhat < 0

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True, False, False,
        False, False, False,  True,  True, False, False, False, False,
        False,  True,  True, False, False, False, False, False,  True,
         True, False, False, False, False,  True,  True,  True, False,
        False, False, False, False,  True,  True, False, False, False,
        False, False,  True,  True, False, False,  True,  True, False,
         True,  True, False, False, False,  True],
       [False, False, False, False, False,  True,  True, False, False,
        False, False, False,  True,  True, False, False, False, False,
        False,  True,  True, False, False, False, False, False,  True,
         True, False, False, False, False,  True,  True,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True, False, False,
        False, False, False,  True,  True, False, False, False, False,
        False,  True,  True, False, False, False, False,  True,  True,
         True, False, False, False, False, False,  True,  True, False,
        False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False]])

In [100]:
from numpy.linalg import inv
inv(W)

array([[ 5.14312714e-03, -8.00510802e-03, -6.93128622e-03,
        -9.24212252e-04, -4.00128356e-03, -4.86892310e-03,
        -4.95838006e-03, -5.23564905e-03, -8.92471930e-04,
        -3.12618623e-04],
       [-8.00510802e-03,  8.72279652e-02, -9.91608885e-03,
        -1.97791077e-02,  1.62778258e-02,  1.64664185e-02,
         4.55478125e-03, -3.23305229e-03,  3.42161023e-03,
        -5.62396045e-04],
       [-6.93128622e-03, -9.91608885e-03,  4.56705791e-02,
        -9.28425715e-03,  1.99184055e-03, -9.96468867e-05,
         7.94654112e-03,  1.22496548e-02,  4.92912817e-04,
        -6.43377746e-03],
       [-9.24212252e-04, -1.97791077e-02, -9.28425715e-03,
         4.75340900e-02, -4.93359490e-03, -2.89388602e-03,
         3.89669431e-03,  7.26076397e-03, -7.51920268e-03,
        -9.47408118e-03],
       [-4.00128356e-03,  1.62778258e-02,  1.99184055e-03,
        -4.93359490e-03,  5.23076207e-02, -2.46754168e-02,
        -4.75764054e-03,  7.33242246e-04, -1.21724811e-03,
         1.19113177e-03],
       [-4.86892310e-03,  1.64664185e-02, -9.96468867e-05,
        -2.89388602e-03, -2.46754168e-02,  7.07057335e-02,
        -1.89537619e-02,  9.94299246e-04,  5.99838065e-03,
         1.54365099e-04],
       [-4.95838006e-03,  4.55478125e-03,  7.94654112e-03,
         3.89669431e-03, -4.75764054e-03, -1.89537619e-02,
         4.92339837e-02, -8.72383601e-03, -4.82043276e-03,
         3.75406138e-03],
       [-5.23564905e-03, -3.23305229e-03,  1.22496548e-02,
         7.26076397e-03,  7.33242246e-04,  9.94299246e-04,
        -8.72383601e-03,  5.78767167e-02, -7.19482170e-03,
        -7.72059978e-03],
       [-8.92471930e-04,  3.42161023e-03,  4.92912817e-04,
        -7.51920268e-03, -1.21724811e-03,  5.99838065e-03,
        -4.82043276e-03, -7.19482170e-03,  3.15535913e-02,
        -9.05171925e-03],
       [-3.12618623e-04, -5.62396045e-04, -6.43377746e-03,
        -9.47408118e-03,  1.19113177e-03,  1.54365099e-04,
         3.75406138e-03, -7.72059978e-03, -9.05171925e-03,
         3.09364521e-02]])

In [101]:
YminT = fcProphet.mint_reconcile(Yhat,W,S)

In [210]:
print(YminT)
print(YminT.shape)

[[ 1.72872798e+02  1.77174696e+02  1.80474662e+02  1.78354454e+02
   1.73557744e+02  3.48999729e+00  3.50065319e+00  1.69241127e+02
   1.78669093e+02  1.80629893e+02  1.78146247e+02  1.67697504e+02
   2.64799598e+00  2.41311798e+00  1.68867348e+02  1.77285348e+02
   1.79211008e+02  1.76774335e+02  1.66416471e+02  1.62252932e+00
   1.68397975e+00  1.69321952e+02  1.77368738e+02  1.79793143e+02
   1.77901858e+02  1.63004213e+02 -1.71104313e+01 -1.64486397e+01
   1.45597807e+02  1.65355338e+02  1.68293301e+02  1.66855925e+02
   6.37699532e+00 -1.14176525e+01 -1.05561217e+01  1.65754377e+02
   1.70553984e+02  1.74145791e+02  1.72472801e+02  1.67307491e+02
  -6.59342791e+00 -6.27557183e+00  1.70183863e+02  1.74281852e+02
   1.77391115e+02  1.68504463e+02  1.67177633e+02 -6.87134638e+00
  -7.38092756e+00  1.68277847e+02  1.71618688e+02  1.44701494e+02
   1.41601127e+02  1.60554580e+02 -1.18396476e+01 -1.26889415e+01
   1.62739021e+02  1.65960613e+02  1.67308875e+02  7.87376872e+00]
 [ 1.09112641e+01  1.00746968e+01  1.09300949e+01  1.06663189e+01
   1.14749662e+01 -1.29400829e+00 -1.32288373e+00  1.07812403e+01
   9.92185767e+00  1.07671477e+01  1.05031447e+01  1.13320468e+01
  -1.45760452e+00 -1.48667566e+00  1.06278662e+01  9.75770040e+00
   1.06028184e+01  1.03386488e+01  1.11678422e+01 -1.62242159e+00
  -1.65164911e+00  5.08708154e+00  9.59242116e+00  1.04373905e+01
   1.01730764e+01  1.09794544e+01 -1.82156817e+00 -1.85091529e+00
   1.02898385e+01  9.42737255e+00  1.02722760e+01  1.00079219e+01
  -6.00348340e-01 -1.98781375e+00 -2.01709806e+00  1.01279531e+01
   9.29087026e+00  1.01065460e+01  9.84243947e+00  1.06802836e+01
  -2.15264856e+00 -2.18153360e+00  9.93453933e+00  9.09794901e+00
   9.95241257e+00  9.70097196e+00  5.22387037e+00 -2.31381739e+00
  -2.34206318e+00  9.77465682e+00  8.93871287e+00  9.81053071e+00
   9.54761279e+00  1.03324781e+01 -2.47064874e+00 -2.49838020e+00
   9.61880451e+00  8.78326965e+00  9.62989014e+00 -2.04913392e+00]
 [ 1.27378222e+01  1.22620064e+01  1.22630131e+01  1.15479732e+01
   1.23985650e+01  1.79600037e+00  1.77538651e+00  1.27838857e+01
   1.22260470e+01  1.21907147e+01  1.14748584e+01  1.23982677e+01
   1.72136861e+00  1.70005116e+00  9.73040744e+00  1.21493983e+01
   1.21134477e+01  1.13969926e+01  1.23214490e+01  1.64234783e+00
   1.62046820e+00  1.25587160e+01  1.20687160e+01  1.20322309e+01
   1.13152563e+01  1.21576900e+01  1.43991024e+00  1.41760066e+00
   3.98835538e+00  1.19888628e+01  1.19521407e+01  1.12350223e+01
   6.57168316e+00  1.35575387e+00  1.33367008e+00  1.24893049e+01
   1.20116355e+01  1.18698378e+01  1.11536095e+01  1.21091662e+01
   1.27666934e+00  1.25602094e+00  1.23074771e+01  1.18315784e+01
   8.81362982e+00  1.11585320e+01  9.20960407e+00  1.21076423e+00
   1.19241400e+00  1.22461964e+01  1.17726214e+01  1.18326583e+01
   1.11207031e+01  7.95198345e+00  1.16045262e+00  1.14395145e+00
   1.21994045e+01  1.17273003e+01  1.16967511e+01  5.47378167e+00]
 [ 3.05461780e+01  3.24026166e+01  3.46717484e+01  3.38346119e+01
   3.19658661e+01 -5.91367299e+00 -6.06280661e+00  3.36673084e+01
   3.27555490e+01  3.36274247e+01  3.24660915e+01  3.24959062e+01
  -7.87697172e+00 -8.28416801e+00  1.54798085e+01  3.01236497e+01
   3.08515184e+01  2.95911346e+01  2.96175774e+01 -1.08089282e+01
  -1.11736314e+01  2.63503556e+01  2.74542919e+01  2.83540108e+01
   2.73013337e+01  2.51215265e+01 -1.61869637e+01 -1.62685571e+01
   2.39536416e+01  2.66674893e+01  2.78692456e+01  2.71120261e+01
  -9.73000030e+00 -1.59479541e+01 -1.57880134e+01  2.87653758e+01
   3.07179213e+01  2.88970706e+01  2.82545781e+01  2.97978143e+01
  -1.46834278e+01 -1.45150339e+01  2.68415522e+01  2.87395792e+01
   3.09616116e+01  3.15187669e+01  3.25411281e+01 -1.39360019e+01
  -1.39147177e+01  2.72899047e+01  2.90357154e+01 -7.14053067e+00
  -8.02748069e+00  2.74763606e+01 -1.41699202e+01 -1.42451728e+01
   2.68817773e+01  2.85698749e+01  2.96546359e+01 -6.38345211e+00]
 [ 3.49119692e+01  3.46557736e+01  3.50542551e+01  3.57821755e+01
   3.64147569e+01  9.16763281e-01  1.18703498e+00  2.14274750e+01
   3.67055365e+01  3.68665054e+01  3.74578686e+01  3.81998149e+01
   2.24014212e+00  2.30327904e+00  3.83724581e+01  3.73711497e+01
   3.72999234e+01  3.76622923e+01  3.81903118e+01  2.01918387e+00
   1.89676264e+00  3.74065371e+01  3.66713745e+01  3.64999730e+01
   3.67968534e+01  3.69926332e+01  6.87480223e-01  6.10080193e-01
   3.69529969e+01  3.60401672e+01  3.60142293e+01  3.64836719e+01
   3.38571299e-01  7.67548416e-01  9.15048405e-01  3.75451374e+01
   3.72009257e+01  3.70070364e+01  3.76900034e+01  3.86937024e+01
   2.34283292e+00  2.63566427e+00  3.89859043e+01  3.87199874e+01
   3.90780005e+01  3.99237658e+01  3.51460606e+01  4.17880814e+00
   4.35383205e+00  4.05495254e+01  4.00952362e+01  4.04582199e+01
   4.08980403e+01  4.08735121e+01  4.54591805e+00  4.43099395e+00
   4.03331149e+01  3.95876387e+01  3.93262516e+01  2.93768419e+00]
 [ 3.66502257e+01  3.65118434e+01  3.70566855e+01  3.67106081e+01
   3.62273282e+01 -1.37266960e+00 -1.53870571e+00  3.58013386e+01
   3.54248843e+01  3.59320288e+01  3.57099328e+01  3.56611334e+01
  -2.05359182e+00 -2.02454593e+00  3.56810735e+01  3.53935621e+01
   3.61559017e+01  3.62037908e+01  2.14383426e+01 -9.90291192e-01
  -6.70473598e-01  3.69062875e+01  3.73166478e+01  3.83466110e+01
   3.86436247e+01  3.87901903e+01  1.40482630e+00  1.88699646e+00
   4.03756093e+01  4.05620165e+01  4.16290034e+01  4.19156739e+01
   4.28838721e+00  4.49397785e+00  4.81916631e+00  4.31623740e+01
   4.34533495e+01  4.38188210e+01  4.37793437e+01  4.39458751e+01
   5.61785433e+00  5.54218655e+00  4.30614511e+01  4.29367130e+01
   4.34259954e+01  2.81517783e+01  3.72283150e+01  3.96697514e+00
   3.57045849e+00  4.08080651e+01  4.04460357e+01  4.09806211e+01
   4.04043300e+01  3.93489032e+01  1.03901613e+00  6.68253280e-01
   3.79842818e+01  3.77505706e+01  3.81019000e+01  1.74963305e-03]
 [ 3.37249656e+01  3.48093722e+01  3.41971932e+01  3.42771027e+01
   3.36252451e+01  2.53717805e-01  4.99233657e-01  3.55184637e+01
   3.64730529e+01  3.58809291e+01  3.60894948e+01  2.10680697e+01
   2.23166222e+00  2.51494069e+00  3.76924819e+01  3.84820883e+01
   3.78506272e+01  3.80001223e+01  3.76646140e+01  3.97991329e+00
   4.16782773e+00  3.88279612e+01  3.99357608e+01  3.92078693e+01
   3.92674363e+01  3.85332391e+01  4.63018055e+00  4.76170768e+00
   2.58222526e+01  4.09411419e+01  4.01984378e+01  4.02557963e+01
   5.90706974e+00  5.62937713e+00  5.78472192e+00  2.69311993e+01
   2.80850828e+01  4.13002104e+01  4.13755729e+01  2.67497885e+01
   6.75421120e+00  6.89128734e+00  4.19363295e+01  4.30370277e+01
   4.23701393e+01  4.25235512e+01  2.82123222e+01  7.37024025e+00
   7.36329114e+00  4.22508388e+01  4.31835749e+01  4.25761636e+01
   4.23819302e+01  4.10553454e+01  6.81533417e+00  6.64664018e+00
   4.13865152e+01  4.21897112e+01  4.11163924e+01  7.19170054e+00]
 [ 1.20536076e+01  1.27592731e+01  1.29053604e+01  1.25907985e+01
   1.02561389e+01  1.65547955e+01  1.65530593e+01  1.40752825e+01
   1.34325480e+01  1.29498780e+01  1.25748361e+01  1.13341744e+01
   1.65078282e+01  1.65401728e+01  1.47142014e+01  1.35922403e+01
   1.32475239e+01  1.30430330e+01  1.20279906e+01  1.74042615e+01
   1.76870143e+01  1.44911414e+01  1.52892858e+01  1.52335165e+01
   1.53193755e+01  1.33433214e+01  1.84100690e+01  1.89506711e+01
   1.90836978e+01  1.88867839e+01  1.90049476e+01  1.92273719e+01
   1.80824177e+01  2.24047369e+01  2.29514946e+01  2.32744377e+01
   2.43773111e+01  2.27444264e+01  2.27892139e+01  2.24034741e+01
   2.54898312e+01  2.57450753e+01  2.41296149e+01  2.48878650e+01
   2.49952469e+01  2.53301996e+01  2.62298778e+01  2.61195014e+01
   2.60009149e+01  2.40239794e+01  2.44386207e+01  2.51443236e+01
   2.45209516e+01  2.05143288e+01  2.45660771e+01  2.42560840e+01
   2.21257736e+01  2.24257496e+01  2.16509913e+01  2.16283825e+01]
 [-6.11747538e+00 -5.00606964e+00 -3.47160401e+00 -3.86058378e+00
  -5.35336887e+00 -3.85802659e+00 -3.88454320e+00 -2.61006576e+00
  -4.13405164e+00 -3.70332193e+00 -4.00655584e+00 -2.95107703e+00
  -3.83469318e+00 -3.78198067e+00 -1.15902534e+00 -3.89410598e+00
  -3.40885105e+00 -3.66905522e+00 -2.52868645e+00 -3.45012323e+00
  -3.39483432e+00 -4.36897654e+00 -3.54484453e+00 -3.09946649e+00
  -3.41255860e+00 -5.06482777e+00 -7.34011345e+00 -7.36910180e+00
  -1.66504972e+00 -3.56775472e+00 -3.22207694e+00 -3.63589915e+00
  -3.77847774e+00 -7.89273066e+00 -8.01333680e+00 -1.88983717e+00
  -8.33797759e-01 -4.09479262e+00 -4.56495869e+00 -2.61139068e+00
  -8.89972733e+00 -9.04127313e+00 -6.46642462e+00 -5.40779400e+00
  -4.05359993e+00 -3.04516401e+00  2.58653743e+00 -9.82433531e+00
  -9.91932875e+00 -7.29298618e+00 -6.17935756e+00 -2.75710793e+00
  -3.14589239e+00 -7.61879673e+00 -1.03677290e+01 -1.04092872e+01
  -7.73258880e+00 -6.57211573e+00 -6.17969241e+00 -5.13035375e+00]
 [ 7.45424124e+00  8.70518344e+00  6.86791580e+00  6.80544912e+00
   6.54824632e+00 -3.59290221e+00 -3.70512206e+00  7.79619885e+00
   5.86366919e+00  6.11858641e+00  5.87657617e+00  8.15916801e+00
  -4.83014393e+00 -5.06795545e+00  7.72807643e+00  4.30966519e+00
   4.49809828e+00  4.20737539e+00  6.51703010e+00 -6.55141292e+00
  -6.79750470e+00  2.06284864e+00  2.58508448e+00  2.78100790e+00
   2.49746006e+00 -7.84901440e+00 -1.83342523e+01 -1.85871217e+01
  -1.32035352e+01 -1.55907416e+01 -1.54249025e+01 -1.57456597e+01
  -1.47023074e+01 -2.02405481e+01 -2.05417747e+01 -1.46515681e+01
  -1.37493145e+01 -1.75033648e+01 -1.78470010e+01 -1.44612229e+01
  -2.23390232e+01 -2.26079656e+01 -2.05465802e+01 -1.95610538e+01
  -1.81523215e+01 -1.67579391e+01 -9.20008249e+00 -2.36434810e+01
  -2.36857285e+01 -2.13723339e+01 -2.01124722e+01 -1.62033844e+01
  -1.60990683e+01 -1.93795352e+01 -2.29581476e+01 -2.26820242e+01
  -2.00580619e+01 -1.85013862e+01 -1.76882448e+01 -1.57965900e+01]]
(10, 60)

In [215]:
labels = ["total"] + list(equipos)
YminT_df = pd.DataFrame(YminT, index = labels)

In [216]:
print(YminT_df)

                    0           1           2           3           4   \
total       172.872798  177.174696  180.474662  178.354454  173.557744
EDGE1_6107   10.911264   10.074697   10.930095   10.666319   11.474966
EDGE2_6137   12.737822   12.262006   12.263013   11.547973   12.398565
HALCYON      30.546178   32.402617   34.671748   33.834612   31.965866
HALCYON3     34.911969   34.655774   35.054255   35.782176   36.414757
HALCYON4     36.650226   36.511843   37.056686   36.710608   36.227328
HALCYON5     33.724966   34.809372   34.197193   34.277103   33.625245
SYNERGY      12.053608   12.759273   12.905360   12.590799   10.256139
SYNERGY2     -6.117475   -5.006070   -3.471604   -3.860584   -5.353369
SYNERGY3      7.454241    8.705183    6.867916    6.805449    6.548246

                   5          6           7           8           9   ...  \
total        3.489997   3.500653  169.241127  178.669093  180.629893  ...
EDGE1_6107  -1.294008  -1.322884   10.781240    9.921858   10.767148  ...
EDGE2_6137   1.796000   1.775387   12.783886   12.226047   12.190715  ...
HALCYON     -5.913673  -6.062807   33.667308   32.755549   33.627425  ...
HALCYON3     0.916763   1.187035   21.427475   36.705536   36.866505  ...
HALCYON4    -1.372670  -1.538706   35.801339   35.424884   35.932029  ...
HALCYON5     0.253718   0.499234   35.518464   36.473053   35.880929  ...
SYNERGY     16.554796  16.553059   14.075282   13.432548   12.949878  ...
SYNERGY2    -3.858027  -3.884543   -2.610066   -4.134052   -3.703322  ...
SYNERGY3    -3.592902  -3.705122    7.796199    5.863669    6.118586  ...

                    50          51          52          53         54  \
total       171.618688  144.701494  141.601127  160.554580 -11.839648
EDGE1_6107    8.938713    9.810531    9.547613   10.332478  -2.470649
EDGE2_6137   11.772621   11.832658   11.120703    7.951983   1.160453
HALCYON      29.035715   -7.140531   -8.027481   27.476361 -14.169920
HALCYON3     40.095236   40.458220   40.898040   40.873512   4.545918
HALCYON4     40.446036   40.980621   40.404330   39.348903   1.039016
HALCYON5     43.183575   42.576164   42.381930   41.055345   6.815334
SYNERGY      24.438621   25.144324   24.520952   20.514329  24.566077
SYNERGY2     -6.179358   -2.757108   -3.145892   -7.618797 -10.367729
SYNERGY3    -20.112472  -16.203384  -16.099068  -19.379535 -22.958148

                   55          56          57          58         59
total      -12.688942  162.739021  165.960613  167.308875   7.873769
EDGE1_6107  -2.498380    9.618805    8.783270    9.629890  -2.049134
EDGE2_6137   1.143951   12.199405   11.727300   11.696751   5.473782
HALCYON    -14.245173   26.881777   28.569875   29.654636  -6.383452
HALCYON3     4.430994   40.333115   39.587639   39.326252   2.937684
HALCYON4     0.668253   37.984282   37.750571   38.101900   0.001750
HALCYON5     6.646640   41.386515   42.189711   41.116392   7.191701
SYNERGY     24.256084   22.125774   22.425750   21.650991  21.628382
SYNERGY2   -10.409287   -7.732589   -6.572116   -6.179692  -5.130354
SYNERGY3   -22.682024  -20.058062  -18.501386  -17.688245 -15.796590

[10 rows x 60 columns]

In [217]:
Y_mint_shrk = fcProphet.mint_reconcile(Yhat,W_shrink,S)

In [218]:
print(Y_mint_shrk)
print(Y_mint_shrk.shape)

[[ 1.72861099e+02  1.77164601e+02  1.80467883e+02  1.78347341e+02
   1.73549208e+02  3.47880912e+00  3.48924670e+00  1.69239093e+02
   1.78660956e+02  1.80621658e+02  1.78137601e+02  1.67694277e+02
   2.63513267e+00  2.39997025e+00  1.68867092e+02  1.77275347e+02
   1.79200851e+02  1.76763709e+02  1.66411364e+02  1.60757850e+00
   1.66869169e+00  1.69309436e+02  1.77356493e+02  1.79780692e+02
   1.77888890e+02  1.62989056e+02 -1.71390653e+01 -1.64776513e+01
   1.45590541e+02  1.65340927e+02  1.68278662e+02  1.66840756e+02
   6.36415315e+00 -1.14488565e+01 -1.05876821e+01  1.65746013e+02
   1.70547050e+02  1.74128756e+02  1.72455320e+02  1.67298449e+02
  -6.62672540e+00 -6.30909087e+00  1.70163753e+02  1.74263337e+02
   1.77375601e+02  1.68492780e+02  1.67184830e+02 -6.90549909e+00
  -7.41508591e+00  1.68257315e+02  1.71599971e+02  1.44691640e+02
   1.41591227e+02  1.60535225e+02 -1.18731904e+01 -1.27223163e+01
   1.62719430e+02  1.65942975e+02  1.67291588e+02  7.86046013e+00]
 [ 1.08926744e+01  1.00586558e+01  1.09193231e+01  1.06550152e+01
   1.14614028e+01 -1.31178663e+00 -1.34100898e+00  1.07780083e+01
   9.90892851e+00  1.07540625e+01  1.04894056e+01  1.13269195e+01
  -1.47804470e+00 -1.50756780e+00  1.06274590e+01  9.74180826e+00
   1.05866779e+01  1.03217651e+01  1.11597266e+01 -1.64617889e+00
  -1.67594230e+00  5.06719326e+00  9.57296385e+00  1.04176050e+01
   1.01524701e+01  1.09553705e+01 -1.86706839e+00 -1.89701558e+00
   1.02782919e+01  9.40447385e+00  1.02490137e+01  9.98381733e+00
  -6.20754928e-01 -2.03739781e+00 -2.06724849e+00  1.01146629e+01
   9.27985195e+00  1.00794766e+01  9.81466068e+00  1.06659162e+01
  -2.20555925e+00 -2.23479636e+00  9.90258318e+00  9.06852911e+00
   9.92776034e+00  9.68240857e+00  5.23530695e+00 -2.36808706e+00
  -2.39634180e+00  9.74203211e+00  8.90897134e+00  9.79487147e+00
   9.53188212e+00  1.03017232e+01 -2.52394932e+00 -2.55141368e+00
   9.58767438e+00  8.75524228e+00  9.60242079e+00 -2.07028166e+00]
 [ 1.27201257e+01  1.22467361e+01  1.22527588e+01  1.15372126e+01
   1.23856533e+01  1.77907623e+00  1.75813213e+00  1.27808090e+01
   1.22137391e+01  1.21782582e+01  1.14617795e+01  1.23933868e+01
   1.70191052e+00  1.68016284e+00  9.73001972e+00  1.21342697e+01
   1.20980826e+01  1.13809200e+01  1.23137233e+01  1.61973200e+00
   1.59734224e+00  1.25397833e+01  1.20501935e+01  1.20133960e+01
   1.12956401e+01  1.21347633e+01  1.39659618e+00  1.37371536e+00
   3.97736354e+00  1.19670643e+01  1.19299961e+01  1.12120759e+01
   6.55225705e+00  1.30855219e+00  1.28592925e+00  1.24766532e+01
   1.20011466e+01  1.18440690e+01  1.11271654e+01  1.20954890e+01
   1.22630086e+00  1.20531731e+00  1.22770563e+01  1.18035720e+01
   8.79016207e+00  1.11408605e+01  9.22049115e+00  1.15910206e+00
   1.14074332e+00  1.22151392e+01  1.17443089e+01  1.18177515e+01
   1.11057282e+01  7.92270628e+00  1.10971299e+00  1.09346608e+00
   1.21697701e+01  1.17006195e+01  1.16706016e+01  5.45365003e+00]
 [ 3.05643517e+01  3.24182986e+01  3.46822791e+01  3.38456627e+01
   3.19791259e+01 -5.89629246e+00 -6.04508694e+00  3.36704681e+01
   3.27681889e+01  3.36402171e+01  3.24795231e+01  3.25009187e+01
  -7.85698891e+00 -8.26374337e+00  1.54802067e+01  3.01391862e+01
   3.08672978e+01  2.96076406e+01  2.96255114e+01 -1.07857025e+01
  -1.11498818e+01  2.63697988e+01  2.74733139e+01  2.83733536e+01
   2.73214789e+01  2.51450715e+01 -1.61424816e+01 -1.62234883e+01
   2.39649299e+01  2.66898756e+01  2.78919873e+01  2.71355913e+01
  -9.71005034e+00 -1.58994795e+01 -1.57389851e+01  2.87783687e+01
   3.07286931e+01  2.89235343e+01  2.82817353e+01  2.98118602e+01
  -1.46317011e+01 -1.44629630e+01  2.68727932e+01  2.87683408e+01
   3.09857122e+01  3.15369150e+01  3.25299475e+01 -1.38829466e+01
  -1.38616537e+01  2.73217994e+01  2.90647914e+01 -7.12522183e+00
  -8.01210202e+00  2.75064273e+01 -1.41178123e+01 -1.41933260e+01
   2.69122108e+01  2.85972752e+01  2.96814905e+01 -6.36277758e+00]
 [ 3.48976364e+01  3.46434058e+01  3.50459499e+01  3.57734602e+01
   3.64042994e+01  9.03055958e-01  1.17306019e+00  2.14249831e+01
   3.66955679e+01  3.68564165e+01  3.74472756e+01  3.81958618e+01
   2.22438248e+00  2.28717094e+00  3.83721441e+01  3.73588967e+01
   3.72874789e+01  3.76492747e+01  3.81840546e+01  2.00086669e+00
   1.87803229e+00  3.73912030e+01  3.66563726e+01  3.64847181e+01
   3.67809657e+01  3.69740642e+01  6.52398985e-01  5.74536290e-01
   3.69440943e+01  3.60225120e+01  3.59962938e+01  3.64650870e+01
   3.22837565e-01  7.29318484e-01  8.76381798e-01  3.75348905e+01
   3.71924304e+01  3.69861656e+01  3.76685856e+01  3.86826249e+01
   2.30203811e+00  2.59459801e+00  3.89612657e+01  3.86973043e+01
   3.90589933e+01  3.99094532e+01  3.51548784e+01  4.13696554e+00
   4.31198255e+00  4.05243714e+01  4.00723051e+01  4.04461464e+01
   4.08859117e+01  4.08497997e+01  4.50482264e+00  4.39010448e+00
   4.03091131e+01  3.95660292e+01  3.93050724e+01  2.92137902e+00]
 [ 3.66361096e+01  3.64996626e+01  3.70485060e+01  3.67020246e+01
   3.62170288e+01 -1.38616962e+00 -1.55246915e+00  3.57988844e+01
   3.54150665e+01  3.59220925e+01  3.56995000e+01  3.56572400e+01
  -2.06911312e+00 -2.04041041e+00  3.56807642e+01  3.53814944e+01
   3.61436453e+01  3.61909701e+01  2.14321800e+01 -1.00833134e+00
  -6.88920672e-01  3.68911853e+01  3.73018728e+01  3.83315868e+01
   3.86279772e+01  3.87719022e+01  1.37027563e+00  1.85199012e+00
   4.03668413e+01  4.05446283e+01  4.16113391e+01  4.18973701e+01
   4.27289143e+00  4.45632610e+00  4.78108449e+00  4.31522820e+01
   4.34449827e+01  4.37982658e+01  4.37582498e+01  4.39349651e+01
   5.57767650e+00  5.50174137e+00  4.30371851e+01  4.29143729e+01
   4.34072757e+01  2.81376821e+01  3.72369994e+01  3.92576536e+00
   3.52924192e+00  4.07832914e+01  4.04234514e+01  4.09687303e+01
   4.03923848e+01  3.93255495e+01  9.98542231e-01  6.27982209e-01
   3.79606431e+01  3.77292880e+01  3.80810411e+01 -1.43089400e-02]
 [ 3.37108580e+01  3.47971988e+01  3.41890186e+01  3.42685244e+01
   3.36149519e+01  2.40225941e-01  4.85478527e-01  3.55160109e+01
   3.64632410e+01  3.58709988e+01  3.60790683e+01  2.10641786e+01
   2.21615030e+00  2.49908579e+00  3.76921728e+01  3.84700278e+01
   3.78383783e+01  3.79873094e+01  3.76584552e+01  3.96188403e+00
   4.14939180e+00  3.88128681e+01  3.99209948e+01  3.91928543e+01
   3.92517983e+01  3.85149620e+01  4.59565074e+00  4.72672247e+00
   2.58134899e+01  4.09237642e+01  4.01807842e+01  4.02375036e+01
   5.89158332e+00  5.59174811e+00  5.74666310e+00  2.69211134e+01
   2.80767210e+01  4.12796676e+01  4.13544918e+01  2.67388852e+01
   6.71405762e+00  6.85086658e+00  4.19120782e+01  4.30147011e+01
   4.23514309e+01  4.25094635e+01  2.82210013e+01  7.32905535e+00
   7.32209945e+00  4.22260802e+01  4.31610043e+01  4.25642800e+01
   4.23699923e+01  4.10320057e+01  6.77488471e+00  6.60639342e+00
   4.13628907e+01  4.21684414e+01  4.10955461e+01  7.17565166e+00]
 [ 1.20535952e+01  1.27592624e+01  1.29053532e+01  1.25907910e+01
   1.02561298e+01  1.65547836e+01  1.65530472e+01  1.40752803e+01
   1.34325394e+01  1.29498692e+01  1.25748270e+01  1.13341710e+01
   1.65078146e+01  1.65401589e+01  1.47142011e+01  1.35922297e+01
   1.32475132e+01  1.30430217e+01  1.20279851e+01  1.74042457e+01
   1.76869981e+01  1.44911281e+01  1.52892728e+01  1.52335033e+01
   1.53193617e+01  1.33433054e+01  1.84100387e+01  1.89506404e+01
   1.90836901e+01  1.88867686e+01  1.90049321e+01  1.92273558e+01
   1.80824041e+01  2.24047038e+01  2.29514611e+01  2.32744289e+01
   2.43773037e+01  2.27444084e+01  2.27891954e+01  2.24034645e+01
   2.54897959e+01  2.57450398e+01  2.41295935e+01  2.48878453e+01
   2.49952304e+01  2.53301872e+01  2.62298854e+01  2.61194652e+01
   2.60008787e+01  2.40239576e+01  2.44386009e+01  2.51443132e+01
   2.45209411e+01  2.05143083e+01  2.45660415e+01  2.42560486e+01
   2.21257528e+01  2.24257309e+01  2.16509729e+01  2.16283684e+01]
 [-6.09500645e+00 -4.98668119e+00 -3.45858438e+00 -3.84692118e+00
  -5.33697512e+00 -3.83653826e+00 -3.86263557e+00 -2.60615931e+00
  -4.11842442e+00 -3.68750606e+00 -3.98994967e+00 -2.94487983e+00
  -3.80998754e+00 -3.75672876e+00 -1.15853307e+00 -3.87489746e+00
  -3.38934231e+00 -3.64864813e+00 -2.51887729e+00 -3.42140825e+00
  -3.36547164e+00 -4.34493797e+00 -3.52132686e+00 -3.07555214e+00
  -3.38765216e+00 -5.03571804e+00 -7.28511824e+00 -7.31338129e+00
  -1.65109354e+00 -3.54007751e+00 -3.19396029e+00 -3.60676446e+00
  -3.75381270e+00 -7.83279939e+00 -7.95272098e+00 -1.87377355e+00
  -8.20480141e-01 -4.06207438e+00 -4.53138303e+00 -2.59402506e+00
  -8.83577523e+00 -8.97689549e+00 -6.42779986e+00 -5.37223476e+00
  -4.02380328e+00 -3.02272680e+00  2.57271427e+00 -9.75874064e+00
  -9.85372326e+00 -7.25355334e+00 -6.14340956e+00 -2.73818092e+00
  -3.12687905e+00 -7.58162395e+00 -1.03033057e+01 -1.03451867e+01
  -7.69496242e+00 -6.53823960e+00 -6.14649076e+00 -5.10479290e+00]
 [ 7.48075489e+00  8.72806207e+00  6.88327914e+00  6.82157117e+00
   6.56759117e+00 -3.56754569e+00 -3.67927076e+00  7.80080852e+00
   5.88210953e+00  6.13724935e+00  5.89617167e+00  8.16648079e+00
  -4.80099094e+00 -5.03815785e+00  7.72865732e+00  4.33233150e+00
   4.52111886e+00  4.23145603e+00  6.52860504e+00 -6.51752886e+00
  -6.76285633e+00  2.09121448e+00  2.61283565e+00  2.80922715e+00
   2.52685000e+00 -7.81466452e+00 -1.82693572e+01 -1.85213707e+01
  -1.31870667e+01 -1.55580821e+01 -1.53917245e+01 -1.57112804e+01
  -1.46732024e+01 -2.01698284e+01 -2.04702472e+01 -1.46326128e+01
  -1.37335996e+01 -1.74647569e+01 -1.78073813e+01 -1.44407312e+01
  -2.22635588e+01 -2.25319991e+01 -2.05010025e+01 -1.95190934e+01
  -1.81171611e+01 -1.67314628e+01 -9.21639401e+00 -2.35660784e+01
  -2.36083131e+01 -2.13258026e+01 -2.00700530e+01 -1.61810503e+01
  -1.60766323e+01 -1.93356708e+01 -2.28821272e+01 -2.26063847e+01
  -2.00136623e+01 -1.84614119e+01 -1.76490664e+01 -1.57664279e+01]]
(10, 60)

In [219]:
y_mint_shrk_df = pd.DataFrame(Y_mint_shrk, index = labels)
print(y_mint_shrk_df.head(5))

                    0           1           2           3           4   \
total       172.861099  177.164601  180.467883  178.347341  173.549208
EDGE1_6107   10.892674   10.058656   10.919323   10.655015   11.461403
EDGE2_6137   12.720126   12.246736   12.252759   11.537213   12.385653
HALCYON      30.564352   32.418299   34.682279   33.845663   31.979126
HALCYON3     34.897636   34.643406   35.045950   35.773460   36.404299

                  5         6           7           8           9   ...  \
total       3.478809  3.489247  169.239093  178.660956  180.621658  ...
EDGE1_6107 -1.311787 -1.341009   10.778008    9.908929   10.754062  ...
EDGE2_6137  1.779076  1.758132   12.780809   12.213739   12.178258  ...
HALCYON    -5.896292 -6.045087   33.670468   32.768189   33.640217  ...
HALCYON3    0.903056  1.173060   21.424983   36.695568   36.856416  ...

                    50          51          52          53         54  \
total       171.599971  144.691640  141.591227  160.535225 -11.873190
EDGE1_6107    8.908971    9.794871    9.531882   10.301723  -2.523949
EDGE2_6137   11.744309   11.817751   11.105728    7.922706   1.109713
HALCYON      29.064791   -7.125222   -8.012102   27.506427 -14.117812
HALCYON3     40.072305   40.446146   40.885912   40.849800   4.504823

                   55          56          57          58        59
total      -12.722316  162.719430  165.942975  167.291588  7.860460
EDGE1_6107  -2.551414    9.587674    8.755242    9.602421 -2.070282
EDGE2_6137   1.093466   12.169770   11.700620   11.670602  5.453650
HALCYON    -14.193326   26.912211   28.597275   29.681491 -6.362778
HALCYON3     4.390104   40.309113   39.566029   39.305072  2.921379

[5 rows x 60 columns]

In [ ]:
def summarize_group(g):
    g = g.sort_values('ds')
    mask = g['y'].isna()

    return pd.Series({
        'size': len(g),
        'min_date':g['ds'].min(),
        'max_date':g['ds'].max(),
        'first_nan_date': g.loc[mask, 'ds'].iloc[0] if mask.any() else pd.NaT,
        'first_nan_position': np.where(mask)[0][0] if mask.any() else None
    })
summary_pred = results.groupby('equipo').apply(summarize_group)
summary_pred

In [ ]:
summary = df.groupby('equipo').agg(
    size = ('equipo', 'size'),
    min_date = ('ds', 'min'),
    max_date = ('ds', 'max')
)

summary

In [ ]:
W = np.cov(residual_df.T)
W += np.eye(W.shape[0]) * 1e-6

In [ ]:
lw = LedoitWolf()
W_shrink = lw.fit(residual_df.T).covariance_

In [ ]:
n = len(equipos)

S = np.vstack([
    np.ones((1,n)),
    np.eye(n)
])

In [304]:
residuals_df.shape

(10, 1399)

In [301]:
W.shape

(1399, 1399)

In [302]:
S.shape

(10, 9)

In [305]:
inv(W).shape

(1399, 1399)